#!/bin/sh

# Pull in collector support functions
. "${COLLECTOR_HOME}"/collectorlib

preModule userdata

#Define and create output folders
USERDATA_DIR="${ALL_MODULES_BASE_OUTPUT_DIR}"/sensitive/userdata
mkdir -p "${USERDATA_DIR}"

if [ -w "${USERDATA_DIR}" ]
then
    logAndRunCmd "cat /etc/sudoers &> \"${USERDATA_DIR}\"/etc_sudoers"
    logAndRunCmd "cat /etc/passwd  &> \"${USERDATA_DIR}\"/etc_passwd"
    logAndRunCmd "cat /etc/group &> \"${USERDATA_DIR}\"/etc_group"
else
    echo "Could not create userdata output directory."
fi

postModule userdata