/*
 * Copyright (C) 2005 Layer 7 Technologies Inc.
 *
 */

package com.l7tech.server;

import com.l7tech.policy.AllAssertions;
import com.l7tech.policy.assertion.Assertion;
import com.l7tech.proxy.BridgeServlet;
import com.l7tech.server.identity.cert.CSRHandler;
import com.l7tech.server.policy.PolicyServlet;
import com.l7tech.common.License;
import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

import java.io.PrintStream;
import java.util.*;
import java.util.logging.Logger;

/**
 * @author mike
 * @noinspection JavaDoc
 */
public class GatewayFeatureSetsTest extends TestCase {
    /** @noinspection UnusedDeclaration*/
    private static Logger log = Logger.getLogger(GatewayFeatureSetsTest.class.getName());

    public GatewayFeatureSetsTest(String name) {
        super(name);
    }

    public static Test suite() {
        return new TestSuite(GatewayFeatureSetsTest.class);
    }

    public static void main(String[] args) {
        junit.textui.TestRunner.run(suite());
    }

    /** Ensures that the feature sets tree is internally consistent and assembles itself without error, and emits wiki doc. */
    public void testEmitWikiDocs() throws Exception {
        Map<String, GatewayFeatureSet> profiles = GatewayFeatureSets.getProductProfiles();
        Map<String, GatewayFeatureSet> roots = GatewayFeatureSets.getRootFeatureSets();
        Map<String, GatewayFeatureSet> all = GatewayFeatureSets.getAllFeatureSets();

        Set<String> visited = new HashSet<String>();
        PrintStream out = System.out;

        Map<String, GatewayFeatureSet> services = new LinkedHashMap<String, GatewayFeatureSet>();
        Set<String> allServNames = new LinkedHashSet<String>(Arrays.asList(ALL_SERVICES));
        for (String servName : allServNames) {
            GatewayFeatureSet serv = all.get(servName);
            assertNotNull(serv);
            services.put(servName, serv);
        }

        emit(out, "Service Names", services, new HashSet<String>(), false);
        emit(out, "Product Profiles", profiles, visited, true);
        emit(out, "Building Blocks", roots, visited, true);
    }

    private void emit(PrintStream out, String what, Map<String, GatewayFeatureSet> sets, Set<String> visited, boolean includeLastTwoColumns) {
        out.println("\n\n<!-- Begin generated by " + getClass().getName() + " -- do not edit below this line -- " + what + " -->");
        String lasttwoHeaders = includeLastTwoColumns ? "!! Included Feature Sets !! Notes" : "";
        out.println("{| border=\"1\" cellpadding=\"3\" cellspacing=\"0\" style=\"font-size: 90%; border: gray solid 2px; border-collapse: collapse; text-align: left; width: 95%\" \n" +
                "|- \n" +
                "! Name !! Short Description " + lasttwoHeaders);
        for (Map.Entry<String, GatewayFeatureSet> entry : sets.entrySet()) {
            String name = entry.getKey();
            GatewayFeatureSet fs = entry.getValue();
            if (visited.contains(name)) continue;
            visited.add(name);
            out.println("|-");
            out.println("| " + name + " || " + fs.desc + (includeLastTwoColumns ? " || " : ""));
            for (GatewayFeatureSet dep : fs.sets) {
                out.println("* " + dep.name);
            }
            if (includeLastTwoColumns)
                out.println("|| " + fs.getNote());
        }
        out.println("|}");
        out.println("<!-- End generated by " + getClass().getName() + " -- do not edit above this line -- " + what + " -->\n");
    }

    public void testAllAssertionsReachableThroughProfileAll() throws Exception {
        GatewayFeatureSet profileAll = GatewayFeatureSets.getBestProductProfile();

        Assertion[] allAssertions = AllAssertions.SERIALIZABLE_EVERYTHING;
        for (Assertion assertion : allAssertions) {
            String name = GatewayFeatureSets.getFeatureSetNameForAssertion(assertion.getClass());
            if (!profileAll.contains(name))
                throw new RuntimeException("Assertion is not enabled by the full-featured Product Profile: " +
                        assertion.getClass() + " (feature set name would be " + name + ")");
        }
    }

    public void testAllOptionalAssertionsHaveAccessToModuleLoading() throws Exception {
        Map<String, GatewayFeatureSet> profiles = GatewayFeatureSets.getProductProfiles();

        License.FeatureSetExpander expander = GatewayFeatureSets.getFeatureSetExpander();
        for (String profileName : profiles.keySet()) {
            //noinspection unchecked
            Set<String> expanded = expander.getAllEnabledFeatures(new HashSet<String>(Arrays.asList(profileName)));

            boolean allowsModuleLoading = expanded.contains(GatewayFeatureSets.SERVICE_MODULELOADER);

            for (String name : expanded) {
                if (GatewayFeatureSets.isOptionalModularAssertion(name))
                    assertTrue("Product profile " + profileName + " that enables optional modular assertion " + name + " must also enable " + GatewayFeatureSets.SERVICE_MODULELOADER, allowsModuleLoading);
            }

            if (expanded.contains("set:modularAssertions"))
                assertTrue(allowsModuleLoading);
        }
    }

    public void testEverythingMapped() throws Exception {
        Map<String, GatewayFeatureSet> allSets = GatewayFeatureSets.getAllFeatureSets();

        Assertion[] allAssertions = AllAssertions.SERIALIZABLE_EVERYTHING;
        for (Assertion assertion : allAssertions) {
            String name = GatewayFeatureSets.getFeatureSetNameForAssertion(assertion.getClass());
            if (!allSets.containsKey(name))
                throw new RuntimeException("Assertion is not present in any Feature Set: " +
                        assertion.getClass() + " (feature set name would be " + name + ")");
        }

        for (String name : ALL_SERVICES) {
            if (!allSets.containsKey(name))
                throw new RuntimeException("Servlet is not present in any Feature Set: " + name);
        }
    }

    private static final String[] ALL_SERVICES = {
            "service:MessageProcessor", // Not named after a servlet
            "service:Admin",            // Not named after a servlet
            "service:HttpMessageInput", // Not named after a servlet
            "service:JmsMessageInput",  // Not named after a servlet
            "service:CSRHandler",       GatewayFeatureSets.getFeatureSetNameForServlet(CSRHandler.class),
            "service:Passwd",           GatewayFeatureSets.getFeatureSetNameForServlet(PasswdServlet.class),
            "service:Policy",           GatewayFeatureSets.getFeatureSetNameForServlet(PolicyServlet.class),
            "service:TokenService",     GatewayFeatureSets.getFeatureSetNameForServlet(TokenServiceServlet.class),
            "service:SnmpQuery",        GatewayFeatureSets.getFeatureSetNameForServlet(SnmpQueryServlet.class),
            "service:WsdlProxy",        GatewayFeatureSets.getFeatureSetNameForServlet(WsdlProxyServlet.class),
            "service:Bridge",           GatewayFeatureSets.getFeatureSetNameForServlet(BridgeServlet.class),
            "service:TrustStore",       // Not named after a servlet
            "service:ModuleLoader",     // Not named after a servlet
    };

    /** Makes sure that all registered services are included in ALL_SERVICES.  Dual of testAllServicesMapped. */
    public void testAllServicesKnown() throws Exception {
        GatewayFeatureSet profileAll = GatewayFeatureSets.getBestProductProfile();

        Set<String> allServs = new HashSet<String>(Arrays.asList(ALL_SERVICES));
        Set<String> names = new HashSet<String>();
        profileAll.collectAllFeatureNames(names);

        for (String name : names) {
            if (name.startsWith("service:") && !allServs.contains(name))
                throw new RuntimeException("Service is registered as a feature but is not present in ALL_SERVICES: " + name);
        }
    }

    /** Makes sure that all services in ALL_SERVICES are registered.  Dual of testAllServicesKnown. */
    public void testAllServicesMapped() throws Exception {
        GatewayFeatureSet profileAll = GatewayFeatureSets.getBestProductProfile();

        Assertion[] allAssertions = AllAssertions.SERIALIZABLE_EVERYTHING;
        for (String name : ALL_SERVICES) {
            if (!profileAll.contains(name))
                throw new RuntimeException("Servlet is not enabled by the full-featured Product Profile: " + name);
        }

        for (Assertion assertion : allAssertions) {
            String name = GatewayFeatureSets.getFeatureSetNameForAssertion(assertion.getClass());
            assertNotNull(name);
        }
    }

    public void testAllAssertionsProfiled() throws Exception {
        Map<String, GatewayFeatureSet> allProfiles = GatewayFeatureSets.getProductProfiles();
        GatewayFeatureSet allProfilesSet =
                new GatewayFeatureSet("EVERYTHING_PROFILED", "", null,
                                                        allProfiles.values().toArray(new GatewayFeatureSet[0]));

        Assertion[] allAssertions = AllAssertions.SERIALIZABLE_EVERYTHING;
        for (Assertion assertion : allAssertions) {
            String name = GatewayFeatureSets.getFeatureSetNameForAssertion(assertion.getClass());
            if (!allProfilesSet.contains(name))
                throw new RuntimeException("Assertion is not enabled by any root-level Product Profile: " +
                        assertion.getClass() + " (feature set name would be " + name + ")");
        }


    }
}
