package com.l7tech.console.panels;

import com.l7tech.common.security.TrustedCertAdmin;
import com.l7tech.common.util.Locator;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.security.cert.*;
import java.security.NoSuchAlgorithmException;
import java.io.*;
import java.net.URL;
import java.rmi.RemoteException;
import java.util.logging.Level;

/**
 * <p> Copyright (C) 2004 Layer 7 Technologies Inc.</p>
 * <p/>
 * $Id$
 */
public class CertDetailsPanel extends WizardStepPanel {
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout( new GridLayoutManager( 3, 3, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
        final JPanel panel1 = new JPanel();
        panel1.setLayout( new GridLayoutManager( 3, 1, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
        mainPanel.add( panel1, new GridConstraints( 0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null ) );
        final JLabel label1 = new JLabel();
        label1.setText( "Certificate Details" );
        panel1.add( label1, new GridConstraints( 1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null ) );
        final Spacer spacer1 = new Spacer();
        panel1.add( spacer1, new GridConstraints( 0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension( -1, 10 ), new Dimension( -1, 10 ), null ) );
        final Spacer spacer2 = new Spacer();
        panel1.add( spacer2, new GridConstraints( 2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension( -1, 10 ), new Dimension( -1, 10 ), null ) );
        certScrollPane = new JScrollPane();
        mainPanel.add( certScrollPane, new GridConstraints( 1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null ) );
        final Spacer spacer3 = new Spacer();
        mainPanel.add( spacer3, new GridConstraints( 2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension( -1, 10 ), new Dimension( -1, 10 ), null ) );
    }

    private JPanel mainPanel;
    private JScrollPane certScrollPane;
    private X509Certificate cert;

    public CertDetailsPanel(WizardStepPanel next) {
        super(next);
        initialize();
    }

    private void initialize() {
        setLayout(new BorderLayout());
        add(mainPanel);
    }

     /**
     * Test whether the step is finished and it is safe to finish the wizard.
     *
     * @return true if the panel is valid, false otherwis
     */
     public boolean canFinish() {
        return false;
    }

    public void readSettings(Object settings) throws IllegalArgumentException {
        if (settings != null) {

            if (settings instanceof CertInfo) {

                CertInfo ci = (CertInfo) settings;
                InputStream is = null;
                CertificateFactory cf = null;

                try {

                    cf = CertificateFactory.getInstance("X.509");

                } catch (CertificateException e) {
                    //todo:
                }


                if (ci.getCertDataSource() instanceof File) {

                    try {
                        is = new FileInputStream(((File) ci.getCertDataSource()).getAbsolutePath());

                        cert = (X509Certificate) cf.generateCertificate(is);

                        is.close();
                    } catch (FileNotFoundException fne) {

                    } catch (CertificateException ce) {

                    } catch (IOException ioe) {

                    }
                } else if (ci.getCertDataSource() instanceof URL) {
                    try {

                        URL url = (URL) ci.getCertDataSource();

                        String urlStr = url.getProtocol() + ":" + "//" + url.getHost();

                        if(url.getPort() > 0) {
                            urlStr = urlStr +  ":" + url.getPort();
                        }

                        if(url.getPath() != null) {
                            urlStr += url.getPath();
                        }

                        System.out.println("Retriving cert from URL: " + urlStr);

                        X509Certificate[] certs = getTrustedCertAdmin().retrieveCertFromUrl(urlStr);
                        cert = certs[0];

                        // todo: ignore the rest?

                    } catch (IOException e) {
                        //todo:
                        e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                    } catch ( TrustedCertAdmin.HostnameMismatchException e ) {
                        //todo:
                        e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                    }

                } else if (ci.getCertDataSource() instanceof String) {

                }
            }
        }

        try {
            JComponent certView = getCertView();
            if(certView == null) {
                 certView = new JLabel();
            } else {
                //certScrollPane.setViewportBorder(BorderFactory.createLineBorder(Color.black));
                certScrollPane.setViewportView(certView);;
            }

            revalidate();
            repaint();

        } catch (CertificateEncodingException ee) {
            //todo:
        } catch (NoSuchAlgorithmException ae) {
            //todo:
        }
    }


     /**
     * Store the values of all fields on the panel to the wizard object which is a used for
     * keeping all the modified values. The wizard object will be used for providing the
     * updated values when updating the server.
     *
     * @param settings the object representing wizard panel state
     */
    public void storeSettings(Object settings) {

        if (settings != null) {

            if (settings instanceof CertInfo) {
                CertInfo ci = (CertInfo) settings;

                try {
                    ci.getTrustedCert().setCertificate(cert);
                    ci.getTrustedCert().setName(cert.getSubjectDN().getName());
                    ci.getTrustedCert().setSubjectDn(cert.getSubjectDN().getName());

                } catch (CertificateEncodingException e) {
                    //todo:
                }
            }
        }
    }

    private TrustedCertAdmin getTrustedCertAdmin() throws RuntimeException {
        TrustedCertAdmin tca =
                (TrustedCertAdmin) Locator.
                getDefault().lookup(TrustedCertAdmin.class);
        if (tca == null) {
            throw new RuntimeException("Could not find registered " + TrustedCertAdmin.class);
        }

        return tca;
    }

    /**
     * @return the wizard step label
     */
    public String getStepLabel() {
        return "View Certificate Details";
    }

    /**
     * Returns a properties instance filled out with info about the certificate.
     */
    private JComponent getCertView()
            throws CertificateEncodingException, NoSuchAlgorithmException {
        if (cert == null)
            return null;
        com.l7tech.common.gui.widgets.CertificatePanel i = new com.l7tech.common.gui.widgets.CertificatePanel(cert);
        i.setCertBorderEnabled(false);
        return i;
    }

}
