package com.l7tech.console.panels;

import com.l7tech.common.gui.util.Utilities;
import com.l7tech.common.security.TrustedCert;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.ResourceBundle;
import java.util.Locale;
import java.util.Calendar;
import java.util.logging.Logger;
import java.security.cert.CertificateEncodingException;
import java.security.cert.X509Certificate;
import java.security.cert.CertificateException;
import java.security.NoSuchAlgorithmException;
import java.io.IOException;
import java.text.SimpleDateFormat;

/**
 * <p> Copyright (C) 2004 Layer 7 Technologies Inc.</p>
 * <p> @author fpang </p>
 * $Id$
 */
public class CertPropertiesWindow extends JDialog {

    private JPanel mainPanel;
    private JPanel certGeneralPane;
    private JPanel certDetailsPane;
    private JPanel certUsagePane;
    private JTabbedPane certTabbedPane;
    private JScrollPane certDetailsScrollPane;
    private JTextField certExpiredOnTextField;
    private JTextField certIssuedToTextField;
    private JTextField certIssuedByTextField;
    private JTextField certNameTextField;
    private JCheckBox signingServerCertCheckBox;
    private JCheckBox signingSAMLTokenCheckBox;
    private JCheckBox signingClientCertCheckBox;
    private JCheckBox outboundSSLConnCheckBox;

    private JButton saveButton;
    private JButton cancelButton;
    private TrustedCert trustedCert = null;

    private static ResourceBundle resources = ResourceBundle.getBundle("com.l7tech.console.resources.EditCertsDialog", Locale.getDefault());
    private static Logger logger = Logger.getLogger(CertManagerWindow.class.getName());


    public CertPropertiesWindow(Dialog owner, TrustedCert tc) {
        super(owner, resources.getString("dialog.title"), true);
        trustedCert = tc;
        initialize();
        pack();
        Utilities.centerOnScreen(this);
    }

    private void initialize() {

        JRootPane rp = this.getRootPane();
        rp.setPreferredSize(new Dimension(550, 400));

        Container p = getContentPane();
        p.setLayout(new BorderLayout());
        p.add(mainPanel, BorderLayout.CENTER);

        populateData();

        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                //todo:
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                hide();
                dispose();
            }
        });
    }

    private void populateData() {
        if (trustedCert == null) {
            return;
        }

        X509Certificate cert = null;
        try {
            cert = trustedCert.getCertificate();
        } catch (CertificateException e) {
            //todo:
        } catch (IOException e) {
            //todo:
        }

        // populate the general data
        SimpleDateFormat sdf = new SimpleDateFormat("mm/dd/yyyy");
        Calendar cal = Calendar.getInstance();
        cal.setTime(cert.getNotAfter());
        certExpiredOnTextField.setText(sdf.format(cal.getTime()));

        certIssuedToTextField.setText(cert.getSubjectDN().getName());
        certIssuedByTextField.setText(cert.getIssuerDN().getName());
        certNameTextField.setText(trustedCert.getName());

        // populate the details
        JComponent certView = getCertView(cert);
        if (certView == null) {
            certView = new JLabel();
        } else {
            certDetailsScrollPane.setViewportView(certView);
        }

        // populate the usage
        if (trustedCert.isTrustedForSigningClientCerts()) {
            signingClientCertCheckBox.setSelected(true);
        }

        if (trustedCert.isTrustedForSigningSamlTokens()) {
            signingSAMLTokenCheckBox.setSelected(true);
        }

        if (trustedCert.isTrustedForSigningServerCerts()) {
            signingServerCertCheckBox.setSelected(true);
        }

        if (trustedCert.isTrustedForSsl()) {
            outboundSSLConnCheckBox.setSelected(true);
        }
    }

    /**
     * Returns a properties instance filled out with info about the certificate.
     */
    private JComponent getCertView(X509Certificate cert) {

        com.l7tech.common.gui.widgets.CertificatePanel certPanel = null;
        try {
            certPanel = new com.l7tech.common.gui.widgets.CertificatePanel(cert);
            certPanel.setCertBorderEnabled(false);
        } catch (CertificateEncodingException ee) {
            logger.warning("Unable to decode the certificate: " + trustedCert.getName());
        } catch (NoSuchAlgorithmException ae) {
            logger.warning("Unable to decode the certificate: " + trustedCert.getName() + ", Algorithm is not supported:" + cert.getSigAlgName());
        }

        return certPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        final JPanel _1;
        _1 = new JPanel();
        mainPanel = _1;
        _1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel _2;
        _2 = new JPanel();
        _2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        _1.add(_2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, 0, 3, 3, 1, null, null, null));
        final JButton _3;
        _3 = new JButton();
        saveButton = _3;
        _3.setText("Save");
        _2.add(_3, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, 0, 1, 3, 0, null, null, null));
        final JButton _4;
        _4 = new JButton();
        cancelButton = _4;
        _4.setText("Cancel");
        _2.add(_4, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, 0, 1, 3, 0, null, null, null));
        final com.intellij.uiDesigner.core.Spacer _5;
        _5 = new com.intellij.uiDesigner.core.Spacer();
        _2.add(_5, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 1, 6, 1, null, null, null));
        final JTabbedPane _6;
        _6 = new JTabbedPane();
        certTabbedPane = _6;
        _1.add(_6, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 3, 3, 3, null, new Dimension(200, 200), null));
        final JPanel _7;
        _7 = new JPanel();
        certGeneralPane = _7;
        _7.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(20, 10, 10, 10), -1, -1));
        _6.addTab("General", _7);
        final JLabel _8;
        _8 = new JLabel();
        _8.setText("Certificate Name");
        _7.add(_8, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final JTextField _9;
        _9 = new JTextField();
        certNameTextField = _9;
        _7.add(_9, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, 8, 1, 6, 0, null, new Dimension(150, -1), null));
        final JLabel _10;
        _10 = new JLabel();
        _10.setText("Expired on");
        _7.add(_10, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final JLabel _11;
        _11 = new JLabel();
        _11.setText("Issued by");
        _7.add(_11, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final JLabel _12;
        _12 = new JLabel();
        _12.setText("Issued to");
        _7.add(_12, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final com.intellij.uiDesigner.core.Spacer _13;
        _13 = new com.intellij.uiDesigner.core.Spacer();
        _7.add(_13, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, 0, 2, 1, 6, null, null, null));
        final JTextField _14;
        _14 = new JTextField();
        certIssuedToTextField = _14;
        _7.add(_14, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, 8, 1, 6, 0, null, new Dimension(150, -1), null));
        final JTextField _15;
        _15 = new JTextField();
        certIssuedByTextField = _15;
        _7.add(_15, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, 8, 1, 6, 0, null, new Dimension(150, -1), null));
        final JTextField _16;
        _16 = new JTextField();
        certExpiredOnTextField = _16;
        _16.setText("");
        _7.add(_16, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, 8, 1, 6, 0, null, new Dimension(150, -1), null));
        final JScrollPane _17;
        _17 = new JScrollPane();
        certDetailsScrollPane = _17;
        _6.addTab("Details", _17);
        final JPanel _18;
        _18 = new JPanel();
        certUsagePane = _18;
        _18.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        _6.addTab("Usage", _18);
        final JPanel _19;
        _19 = new JPanel();
        _19.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(10, 10, 10, 10), -1, -1));
        _18.add(_19, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 3, 3, 3, null, null, null));
        final JCheckBox _20;
        _20 = new JCheckBox();
        outboundSSLConnCheckBox = _20;
        _20.setText("Outbound SSL Connections ");
        _19.add(_20, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, 8, 0, 3, 0, null, null, null));
        final JCheckBox _21;
        _21 = new JCheckBox();
        signingClientCertCheckBox = _21;
        _21.setText("Signing Client Certificates");
        _19.add(_21, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, 8, 0, 3, 0, null, null, null));
        final JCheckBox _22;
        _22 = new JCheckBox();
        signingSAMLTokenCheckBox = _22;
        _22.setText("Signing SAML Tokens");
        _19.add(_22, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, 8, 0, 3, 0, null, null, null));
        final JCheckBox _23;
        _23 = new JCheckBox();
        signingServerCertCheckBox = _23;
        _23.setText("Signing Certificates for Outbound SSL Connections");
        _19.add(_23, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, 8, 0, 3, 0, null, null, null));
        final JPanel _24;
        _24 = new JPanel();
        _24.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 0, 10, 0), -1, -1));
        _19.add(_24, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 3, 3, 0, null, null, null));
        final JLabel _25;
        _25 = new JLabel();
        _25.setText("The certificate is intented for:");
        _24.add(_25, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final com.intellij.uiDesigner.core.Spacer _26;
        _26 = new com.intellij.uiDesigner.core.Spacer();
        _18.add(_26, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, 0, 2, 1, 6, null, null, null));
    }


}
