package com.l7tech.console.panels;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.ResourceBundle;
import java.util.Locale;
import java.util.logging.Logger;

/**
 * <p> Copyright (C) 2004 Layer 7 Technologies Inc.</p>
 * <p> @author fpang </p>
 * $Id$
 */
public class CertPropertiesWindow extends JDialog{

    private JPanel mainPanel;
    private JPanel certGeneralPane;
    private JPanel certDetailsPane;
    private JPanel certUsagePane;
    private JTabbedPane certTabbedPane;
    private JScrollPane certDetailsScrollPane;

    private JButton saveButton;
    private JButton cancelButton;

    private static ResourceBundle resources = ResourceBundle.getBundle("com.l7tech.console.resources.EditCertsDialog", Locale.getDefault());
    private static Logger logger = Logger.getLogger(CertManagerWindow.class.getName());


    public CertPropertiesWindow(Dialog owner) {
        super(owner, resources.getString("dialog.title"), true);
        initialize();
        pack();
    }

    private void initialize() {

        JRootPane rp = this.getRootPane();
        rp.setPreferredSize(new Dimension(450, 400));

        Container p = getContentPane();
        p.setLayout(new BorderLayout());
        p.add(mainPanel, BorderLayout.CENTER);

        //certTableScrollPane.setViewportView(getTrustedCertTable());


        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
               //todo:
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                hide();
                dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        final JPanel _1;
        _1 = new JPanel();
        mainPanel = _1;
        _1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel _2;
        _2 = new JPanel();
        _2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        _1.add(_2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, 0, 3, 3, 1, null, null, null));
        final JButton _3;
        _3 = new JButton();
        saveButton = _3;
        _3.setText("Save");
        _2.add(_3, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, 0, 1, 3, 0, null, null, null));
        final JButton _4;
        _4 = new JButton();
        cancelButton = _4;
        _4.setText("Cancel");
        _2.add(_4, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, 0, 1, 3, 0, null, null, null));
        final com.intellij.uiDesigner.core.Spacer _5;
        _5 = new com.intellij.uiDesigner.core.Spacer();
        _2.add(_5, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 1, 6, 1, null, null, null));
        final JTabbedPane _6;
        _6 = new JTabbedPane();
        certTabbedPane = _6;
        _1.add(_6, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 3, 3, 3, null, new Dimension(200, 200), null));
        final JPanel _7;
        _7 = new JPanel();
        certGeneralPane = _7;
        _6.addTab("General", _7);
        final JScrollPane _8;
        _8 = new JScrollPane();
        certDetailsScrollPane = _8;
        _6.addTab("Details", _8);
        final JPanel _9;
        _9 = new JPanel();
        certUsagePane = _9;
        _6.addTab("Usage", _9);
    }

}
