package com.l7tech.console.panels;

import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.GridConstraints;

import javax.swing.*;
import java.awt.*;

/**
 * <p> Copyright (C) 2004 Layer 7 Technologies Inc.</p>
 * <p> @author fpang </p>
 * $Id$
 */
public class VirtualGroupDetailsPanel extends JPanel {

    private JPanel mainPanel;
    private JTextField groupDescTextField;
    private JTextField x509SubjectDNTextField;
    private JTextField emailTextField;
    private VirtualGroupPanel virtualGroupPanel;
    private JLabel emailPatternLabel;

    /**
     * Constructor
     */
    public VirtualGroupDetailsPanel(VirtualGroupPanel p) {
        virtualGroupPanel = p;
        initComponents();
        applyFormSecurity();
    }

    private void applyFormSecurity() {
        virtualGroupPanel.securityFormAuthorizationPreparer.prepare(new Component[]{
            groupDescTextField,
            x509SubjectDNTextField,
            emailTextField
        });

    }

    /**
     * This method is called from within the constructor to
     * initialize the dialog.
     */
    private void initComponents() {
        this.add(mainPanel);

        // Bugzilla #1090 - disable the fields that cannot be tested in rel 3.0        
        emailTextField.setEnabled(false);
        emailPatternLabel.setEnabled(false);
    }

    public JTextField getGroupDescTextField() {
        return groupDescTextField;
    }

    public void setGroupDescTextField(JTextField groupDescTextField) {
        this.groupDescTextField = groupDescTextField;
    }

    public JTextField getX509SubjectDNTextField() {
        return x509SubjectDNTextField;
    }

    public void setX509SubjectDNTextField(JTextField x509SubjectDNTextField) {
        this.x509SubjectDNTextField = x509SubjectDNTextField;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public void setEmailTextField(JTextField emailTextField) {
        this.emailTextField = emailTextField;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// !!! IMPORTANT !!!
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * !!! IMPORTANT !!!
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "  Group Pattern  "));
        final JLabel label1 = new JLabel();
        label1.setText("X509 Subject DN:");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null));
        emailPatternLabel = new JLabel();
        emailPatternLabel.setText("Email:");
        panel1.add(emailPatternLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null));
        x509SubjectDNTextField = new JTextField();
        panel1.add(x509SubjectDNTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null));
        emailTextField = new JTextField();
        emailTextField.setText("");
        panel1.add(emailTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 5, 12, 5), -1, -1));
        mainPanel.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null));
        final JLabel label2 = new JLabel();
        label2.setText("Description:");
        panel2.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null));
        groupDescTextField = new JTextField();
        panel2.add(groupDescTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null));
    }
}
