package com.l7tech.internal.audit;

import com.l7tech.common.io.CertUtils;
import com.l7tech.security.prov.JceProvider;
import com.l7tech.util.ConfigFactory;
import com.l7tech.util.HexUtils;
import com.l7tech.util.Pair;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ObjectInputStream;
import java.security.Security;
import java.security.cert.X509Certificate;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

/**
 *
 */
public class AuditRecordCompatibilityVerifier52Test {
    static boolean PRINTOUT = ConfigFactory.getBooleanProperty( "com.l7tech.internal.audit.testPrintout", false );

    @BeforeClass
    public static void initJceProvider() {
        Security.removeProvider("SunEC");
        // Init jceprovider to ensure a Singature.SHA512withECDSA implementation is available
        JceProvider.init();
    }

    @Test
    public void testSplitFields() throws Exception {
        assertEquals(Arrays.asList(""), AuditRecordCompatibilityVerifier52.splitFields(""));
        assertEquals(Arrays.asList(""), AuditRecordCompatibilityVerifier52.splitFields("\\"));
        assertEquals(Arrays.asList("\\"), AuditRecordCompatibilityVerifier52.splitFields("\\\\"));
        assertEquals(Arrays.asList(":"), AuditRecordCompatibilityVerifier52.splitFields("\\:"));
        assertEquals(Arrays.asList("\\:"), AuditRecordCompatibilityVerifier52.splitFields("\\\\\\:"));
        assertEquals(Arrays.asList("\\:"), AuditRecordCompatibilityVerifier52.splitFields("\\\\\\:\\"));
        assertEquals(Arrays.asList("a"), AuditRecordCompatibilityVerifier52.splitFields("a"));
        assertEquals(Arrays.asList("a", "b"), AuditRecordCompatibilityVerifier52.splitFields("a:b"));
        assertEquals(Arrays.asList("a", "b", "c"), AuditRecordCompatibilityVerifier52.splitFields("a:b:c"));
        assertEquals(Arrays.asList("a", "b", "c", ""), AuditRecordCompatibilityVerifier52.splitFields("a:b:c:"));
        assertEquals(Arrays.asList("a", "", "c", ""), AuditRecordCompatibilityVerifier52.splitFields("a::c:"));
        assertEquals(Arrays.asList("a", ":c", ""), AuditRecordCompatibilityVerifier52.splitFields("a:\\:c:"));
        assertEquals(Arrays.asList("a", "b", "c:"), AuditRecordCompatibilityVerifier52.splitFields("a:b:c\\:"));
        assertEquals(Arrays.asList("a", "b", "[c:d:e]"), AuditRecordCompatibilityVerifier52.splitFields("a:b:[c\\:d\\:e]"));
    }

    @Test
    public void testReplayUpdatesWithDetail() throws Exception {
        replaySignedUpdates(RECORDED_UPDATES_WITHDETAIL);
    }

    @Test
    public void testReplayUpdatesNoDetail() throws Exception {
        replaySignedUpdates(RECORDED_UPDATES_NODETAIL);
    }

    @Test
    public void testReplayUpdatesMessageWithResponse() throws Exception {
        replaySignedUpdates(RECORDED_UPDATES_MESSAGE_WITH_RESPONSE);
    }

    static void replaySignedUpdates(String str) throws Exception {
        @SuppressWarnings({"unchecked"}) List<Pair<Boolean, byte[]>> updates =
                (List<Pair<Boolean, byte[]>>)new ObjectInputStream(new ByteArrayInputStream(HexUtils.decodeBase64(str))).readObject();

        int fieldNum = 0;
        for (Pair<Boolean, byte[]> update : updates) {
            if (update.left) {
                if (PRINTOUT) System.out.println("update byte array : " + HexUtils.hexDump(update.right) + " (" + new String(update.right) + ")");
                byte[] b = update.right;
                if (b.length == 1 && b[0] == ':') {
                    fieldNum++;
                } else if (b.length == 1 && b[0] == '[') {
                    if (PRINTOUT) System.out.println("Open square bracket in field " + fieldNum);
                }
            } else {
                if (PRINTOUT) System.out.println("update single byte: " + HexUtils.hexDump(update.right) + " (" + new String(update.right) + ")");
            }
        }

    }

    @Test
    public void testVerify53RsaRecord() throws Exception {
        testVerifySignedRecord(SIGNED_53_RSA_RAW, SIGNED_53_RSA_SIG, SIGNED_53_RSA_CERT);
    }

    @Test
    public void testVerify53EcRecord() throws Exception {
        testVerifySignedRecord(SIGNED_53_EC_RAW, SIGNED_53_EC_SIG, SIGNED_53_EC_CERT);
    }

    @Test
    public void testVerify53EcRecord2() throws Exception {
        testVerifySignedRecord(SIGNED_53_EC_RAW2, SIGNED_53_EC_SIG2, SIGNED_53_EC_CERT);
    }

    @Test
    public void testVerify53EcRecord3() throws Exception {
        testVerifySignedRecord(SIGNED_53_EC_RAW3, SIGNED_53_EC_SIG3, SIGNED_53_EC_CERT);
    }

    @Test
    public void testVerify53EcRecord4() throws Exception {
        testVerifySignedRecord(SIGNED_53_EC_RAW4, null, SIGNED_53_EC_CERT);
    }

    @Test
    public void testVerify53EcRecord5() throws Exception {
        testVerifySignedRecord(SIGNED_53_EC_RAW5_MSG, null, SIGNED_53_EC_CERT);
    }

    @Test
    public void testVerify53EcRecord6() throws Exception {
        testVerifySignedRecord(SIGNED_53_EC_RAW6_MSG_EVIL_COMMA, null, SIGNED_53_EC_CERT);
    }

    static void testVerifySignedRecord(String rawRec, String signature, String certPem) throws Exception {
        X509Certificate cert = CertUtils.decodeFromPEM(certPem, false);

        boolean result = new AuditRecordCompatibilityVerifier52(cert).verifyAuditRecordSignature(signature, rawRec);
        assertTrue("Signature made in version 5.3 must verify successfully with compatibility verifier", result);

        // Try altering the signed data
        String hackedRawRec = rawRec.replaceAll("Server", "Sevrer");
        hackedRawRec = hackedRawRec.replaceAll("INFO", "IFNO");
        hackedRawRec = hackedRawRec.replaceAll("Start", "Strat");
        hackedRawRec = hackedRawRec.replaceAll("service", "srevice");
        hackedRawRec = hackedRawRec.replaceAll("processed", "procsesed");

        result = new AuditRecordCompatibilityVerifier52(cert).verifyAuditRecordSignature(signature, hackedRawRec);
        assertFalse("Signature sould not verify when signed record is altered", result);

        if (signature != null) {
            // Try altering the signature
            String hackedSig = signature.replace("w", "x");
            result = new AuditRecordCompatibilityVerifier52(cert).verifyAuditRecordSignature(hackedSig, rawRec);
            assertFalse("Signature sould not verify when signature is altered", result);
        }
    }

    static final String SIGNED_53_RSA_RAW =
            "262144:48b5a4bc60fd4db191ddd5258eab0a35:1281127841525:INFO:Server:Server Initializing:10.7.48.125:::-1:OtcGQsczS1fexrUfXHEl7AbUz9w6v5IVdfQZSrkAtQBNVrmkwGWspuf3qyeHNRbcGXCoqyScj+KyyZQBxaMQhNDYuzwwFzUJczhCAmHxm8A4vnQ8JPsucb6E60SukyEqjkt80rpUC+YqGS3pdzG5NjIqFP2sk4yHqp1fEfcqOWZAdFdtV6raP+fo9kLBxpq/5nMrNwCimLLNJr+jw4U/5DoQ0QjRM2Yc+zKeSnGFbdnRzzaW/vLANxBvIHiLKOxpS6UH2N8jCNG8HqRnQy6ubYVu0zzpWI0CmbfJmq4/OP9SX4B/0H9V4JGA3O5Ai5/pZyPl2iumdO1NRM6YTlBzpA==::::::::::::::::::262144:1200000:Initializing:[1003\\\\\\:Hardware XML acceleration disabled]";
    static final String SIGNED_53_RSA_SIG =
            "OtcGQsczS1fexrUfXHEl7AbUz9w6v5IVdfQZSrkAtQBNVrmkwGWspuf3qyeHNRbcGXCoqyScj+KyyZQBxaMQhNDYuzwwFzUJczhCAmHxm8A4vnQ8JPsucb6E60SukyEqjkt80rpUC+YqGS3pdzG5NjIqFP2sk4yHqp1fEfcqOWZAdFdtV6raP+fo9kLBxpq/5nMrNwCimLLNJr+jw4U/5DoQ0QjRM2Yc+zKeSnGFbdnRzzaW/vLANxBvIHiLKOxpS6UH2N8jCNG8HqRnQy6ubYVu0zzpWI0CmbfJmq4/OP9SX4B/0H9V4JGA3O5Ai5/pZyPl2iumdO1NRM6YTlBzpA==";
    static final String SIGNED_53_RSA_CERT =
            "MIIC/DCCAeSgAwIBAgIIdc0btifRoWkwDQYJKoZIhvcNAQEMBQAwHDEaMBgGA1UEAxMRZGF0YS5s" +
            "N3RlY2gubG9jYWwwHhcNMTAwODA2MTk0NzIwWhcNMjAwODAzMTk0NzIwWjAcMRowGAYDVQQDExFk" +
            "YXRhLmw3dGVjaC5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJn8F0fXK5TO" +
            "R4Il3z9kTAcrhwtmLqJKEutwBAb1vdRCDjiMeKCHVJfrRuXZ6WzxG8U8hn8DC9yaGM/ZXaIb3U2O" +
            "KVqHpHz/tNJYDlbzS4ht5Y788LvFvsUQQ9ukMDqlL1YqbQNuqnD5WddN1B5PrYSqalUFEgJnokbs" +
            "HyWesqclELDhqT57o3UPBaM8EkkMkEnE1L9Z5njWhNJt1t+Dd30lWealxxA9vgxaKJPmm/FF+pvo" +
            "dAKWFhC5MXoJpwvQJcEoy3ZyGWCAmyVTmSGpSQoCsR4IjHuTXTUP5eAQ7Cft5NEb0u1EQYuKrMC4" +
            "+QtPodVbpkltOWoUL7TG5MSgbfkCAwEAAaNCMEAwHQYDVR0OBBYEFKdVwjMgUWeyl6a1+u47a5/1" +
            "O274MB8GA1UdIwQYMBaAFKdVwjMgUWeyl6a1+u47a5/1O274MA0GCSqGSIb3DQEBDAUAA4IBAQBP" +
            "8ShWqR27pvDkiK9E322gvFQ70wJ+e4FVPVvkBsTAmfLja3BJi7GMJe7nvSdQ2f+HxsCV1nukX31s" +
            "p9cUV20IUvrHvZdU0NRMJPVqz/wSGFA6yKYTUS5l/gc1JZN9cs3RBVF07d/4WKXeGtA0hi6R1Rfm" +
            "rrhHZ+IWfGXEyojMwJqTXfTtYm4DxOiXDxGYyUnoDjvbrdERxK8MtupLNfkIfy2UjMrkbutainCk" +
            "1fNNlveVFeq3vG0qGaeGWHMh8v9+8Yo1MFArmCfn7dwGLpQ8fEgVJNOJlRVzXsHx2u8MONgiOuNN" +
            "lRkmHYYPp2iCfIFHaILr3opZWHlIczQ6l/03";

    static final String SIGNED_53_EC_RAW =
            "491521:48b5a4bc60fd4db191ddd5258eab0a35:1281129787980:INFO:Server:Server Initialized:10.7.48.125:::-1:MGQCMDF1Ml/cfAcebqkFpDE7iFsRqizw0cwkdqYRPeowyDXuf6+2sHFu5lpiQxnPbj+XvgIwPJNLlZ0lOiuJqu99N+aK14bIqtvXO14oW+bbrotfWgEff8V8UjKU4dYFh0Td/Ka+::::::::::::::::::491521:1200000:Initialized:[1005\\\\\\:Initializing cryptography subsystem,1006\\\\\\:Using asymmetric cryptography provider\\: JsafeJCE,1007\\\\\\:Using symmetric cryptography provider\\: JsafeJCE]";
    static final String SIGNED_53_EC_SIG =
            "MGQCMDF1Ml/cfAcebqkFpDE7iFsRqizw0cwkdqYRPeowyDXuf6+2sHFu5lpiQxnPbj+XvgIwPJNLlZ0lOiuJqu99N+aK14bIqtvXO14oW+bbrotfWgEff8V8UjKU4dYFh0Td/Ka+";
    static final String SIGNED_53_EC_RAW2 =
            "491527:48b5a4bc60fd4db191ddd5258eab0a35:1281129810391:INFO::View audit data - Start Time\\: Fri Aug 06 11\\:23\\:30 PDT 2010 :192.168.119.1:admin:3:-2:MGQCMGiPgcNiC07XrQJECcqQRRv8vITmcqCPmQDhtRYNF7E2ldPGRpV+Ss8d8txS3qpAhgIwc5JHmhi9N/vDjbgXcUMYrFjsXfOFQekH5RQs0WvzYkirCzRhkZIc68+WNGKQiH8j:491527:<none>:0:O:::::::::::::::::";
    static final String SIGNED_53_EC_SIG2 =
            "MGQCMGiPgcNiC07XrQJECcqQRRv8vITmcqCPmQDhtRYNF7E2ldPGRpV+Ss8d8txS3qpAhgIwc5JHmhi9N/vDjbgXcUMYrFjsXfOFQekH5RQs0WvzYkirCzRhkZIc68+WNGKQiH8j";
    static final String SIGNED_53_EC_RAW3 =
            "557071:48b5a4bc60fd4db191ddd5258eab0a35:1281156543078:WARNING:SecureSpan Gateway:SecureSpan Gateway Policies reloaded:10.7.48.125:::-1:MGUCMQCZccXgm5nCIlm9/CHy9xnIi32LGdqXfkKYfYdWLjqx+XcugBw++zqLf5E5Rm63cngCMD1g51YYL4EpJgwUEWpCeUvUUfFCLrdyx8iMsy2mRdWuf6kYa2zwaFQYw0qJv2dSDg==::::::::::::::::::557071:1000000:Policies reloaded:[3254\\\\\\:Policy Policy for service #655360, test (#720896) is invalid\\: Error creating specific assertion for 'com.l7tech.policy.assertion.composite.AllAssertion'\\: Must have children,3210\\\\\\:\"test\" service (#655360) cannot be read properly and will be discarded from the service cache,3202\\\\\\:Unable to reenable service after license changed/module loaded\\: 655360\\: test]";
    static final String SIGNED_53_EC_SIG3 =
            "MGUCMQCZccXgm5nCIlm9/CHy9xnIi32LGdqXfkKYfYdWLjqx+XcugBw++zqLf5E5Rm63cngCMD1g51YYL4EpJgwUEWpCeUvUUfFCLrdyx8iMsy2mRdWuf6kYa2zwaFQYw0qJv2dSDg==";
    static final String SIGNED_53_EC_RAW4 =
            "557072:48b5a4bc60fd4db191ddd5258eab0a35:1281156553784:WARNING::PolicyVersion #753665 (null) created (activated v2 of policy 720896):192.168.119.1:admin:3:-2:MGYCMQC5RFPwbHZlnLrIoQFZeXObaMHN8mNXHPtbXNkVj6xK6QnaBs8H1E8aRUPb1crCpmwCMQCF6IT0e7P2h1AhxI838TdrplrZTkppWhLP0SaGUPZWWvzt1ftixJChkLl6POlB+aA=:557072:com.l7tech.policy.PolicyVersion:753665:C:::::::::::::::::[3254\\\\\\:Policy Policy for service #655360, test (#720896) is invalid\\: Error creating specific assertion for 'com.l7tech.policy.assertion.composite.AllAssertion'\\: Must have children,3210\\\\\\:\"test\" service (#655360) cannot be read properly and will be discarded from the service cache,3202\\\\\\:Unable to reenable service after license changed/module loaded\\: 655360\\: test]";
    static final String SIGNED_53_EC_RAW5_MSG =
            "557077:48b5a4bc60fd4db191ddd5258eab0a35:1281156572046:WARNING:test [/test]:Message processed successfully:127.0.0.1:::-1:MGYCMQCqbvI6wvz5XScAVMUk1tKhEr8bkuTZKlYO3W7XNCthGv+zw8W9n0xvjtncFB1wlsYCMQCWhsbBr83b6SBt+1WJyovm4LkfubahjxXdbnTnz9IQAZKjMQRXtoXPDvBv8WjO7EQ=:::::557077:0:0000012a49daa49a-1:655360::0::0:5::<ok/>:200:0::::";
    static final String SIGNED_53_EC_RAW6_MSG_EVIL_COMMA =
            "557094:48b5a4bc60fd4db191ddd5258eab0a35:1281156616810:WARNING:test [/test]:Message processed successfully:127.0.0.1:::-1:MGUCMQDoH46S9sfFCvl4srBuzsVmQ7ei/4e3BLz1GTwUUBZ9AT4I9DcwBGXAsM2o6BGSenMCMDLeb8Ey+2fZ3x7ak2KWbutxJOztgxkcwqwqtMr3s+y5F04/NtlWtEnpsTDsojc5zA==:::::557094:0:0000012a49daa49a-d:655360::0::0:5::<ok/>:200:0::::[-4\\\\\\:detail1,-4\\\\\\:evil detail with colon\\:  also, a comma,-4\\\\\\:detail3]";
    static final String SIGNED_53_EC_CERT =
            "MIIBjzCCARagAwIBAgIJAJ+6O0HFA7YzMAoGCCqGSM49BAMDMA0xCzAJBgNVBAMTAmVjMB4XDTEw" +
            "MDgwNjIwMjEyOFoXDTE1MDgwNTIwMjEyOFowDTELMAkGA1UEAxMCZWMwdjAQBgcqhkjOPQIBBgUr" +
            "gQQAIgNiAAROP/rfXsovznt2FAL1HxwC4Nh8OQvM7d9bOLi5RjwFsa7F+mkjyDDdM4vVk9U6evZj" +
            "4PTw+vCRw57sNuDAxGtgKIKxbV348jQmIhw6YeQtMp00dahwmtkZhDAByFQ9ENyjQjBAMB0GA1Ud" +
            "DgQWBBRgTfk5n044E/kQW8aqMRooy/dPmzAfBgNVHSMEGDAWgBRgTfk5n044E/kQW8aqMRooy/dP" +
            "mzAKBggqhkjOPQQDAwNnADBkAjBba6w56vjF6BBv7FPlE2YOcPFA3DfpSuFcgJALWS47APQs6yNJ" +
            "fePRVSRke0hRc4MCMC1jTi7XYB6ob3tBInc0q3eTs6gV9+ntWdJZOSnhXWLbbxmPszvNLjoj+Wn4" +
            "qTM+Wg==";


    // Serialized recording of raw calls made to Signature.update() on a live 5.3 system
    static final String RECORDED_UPDATES_WITHDETAIL =
            "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAACidwQAAADIc3IAFGNvbS5sN3RlY2gudXRpbC5QYWlynqu2nAY3O8UCAAJMAARsZWZ0dAASTGphdmEvbGFuZy9PYmplY3Q7TAAFcmlnaHRxAH4AA3hwc3IAEWphdmEubGFuZy5Cb29sZWFuzSBygNWc+u4CAAFaAAV2YWx1ZXhwAHVyAAJbQqzzF/gGCFTgAgAAeHAAAAABNHNxAH4AAnEAfgAGdXEAfgAHAAAAAThzcQB+AAJxAH4ABnVxAH4ABwAAAAFic3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAE0c3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAAWNzcQB+AAJxAH4ABnVxAH4ABwAAAAE2c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAAWZzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABNHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFic3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATlzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABZHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAE1c3EAfgACcQB+AAZ1cQB+AAcAAAABOHNxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABM3NxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJzcQB+AAUBdXEAfgAHAAAAIDQ4YjVhNGJjNjBmZDRkYjE5MWRkZDUyNThlYWIwYTM1c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAAThzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATNzcQB+AAJxAH4ABnVxAH4ABwAAAAE5c3EAfgACcQB+AAZ1cQB+AAcAAAABM3NxAH4AAnEAfgAGdXEAfgAHAAAAATNzcQB+AAJxAH4ABnVxAH4ABwAAAAEyc3EAfgACcQB+AAZ1cQB+AAcAAAABOHNxAH4AAnEAfgAGdXEAfgAHAAAAATZzcQB+AAJxAH4ABnVxAH4ABwAAAAE3c3EAfgACcQB+AEh1cQB+AAcAAAANMTI4MTEzOTMzMjg2N3NxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABSXNxAH4AAnEAfgAGdXEAfgAHAAAAAU5zcQB+AAJxAH4ABnVxAH4ABwAAAAFGc3EAfgACcQB+AAZ1cQB+AAcAAAABT3NxAH4AAnEAfgBIdXEAfgAHAAAABElORk9zcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAVNzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABcnNxAH4AAnEAfgAGdXEAfgAHAAAAAXZzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABcnNxAH4AAnEAfgBIdXEAfgAHAAAABlNlcnZlcnNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABU3NxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFyc3EAfgACcQB+AAZ1cQB+AAcAAAABdnNxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFyc3EAfgACcQB+AAZ1cQB+AAcAAAABIHNxAH4AAnEAfgAGdXEAfgAHAAAAAVJzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAF5c3EAfgACcQB+AEh1cQB+AAcAAAAMU2VydmVyIFJlYWR5c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAAS5zcQB+AAJxAH4ABnVxAH4ABwAAAAE3c3EAfgACcQB+AAZ1cQB+AAcAAAABLnNxAH4AAnEAfgAGdXEAfgAHAAAAATRzcQB+AAJxAH4ABnVxAH4ABwAAAAE4c3EAfgACcQB+AAZ1cQB+AAcAAAABLnNxAH4AAnEAfgAGdXEAfgAHAAAAATFzcQB+AAJxAH4ABnVxAH4ABwAAAAEyc3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgBIdXEAfgAHAAAACzEwLjcuNDguMTI1c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABLXNxAH4AAnEAfgAGdXEAfgAHAAAAATFzcQB+AAJxAH4ASHVxAH4ABwAAAAItMXNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgBIdXEAfgAHAAAABzEyMDAwMDBzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAVJzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAF5c3EAfgACcQB+AEh1cQB+AAcAAAAFUmVhZHlzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAVtzcQB+AAJxAH4ASHVxAH4ABwAAAAFbc3EAfgACcQB+AAZ1cQB+AAcAAAABM3NxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAE1c3EAfgACcQB+AAZ1cQB+AAcAAAABM3NxAH4AAnEAfgBIdXEAfgAHAAAABDMyNTNzcQB+AAJxAH4ABnVxAH4ABwAAAAFcc3EAfgACcQB+AEh1cQB+AAcAAAABXHNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABKHNxAH4AAnEAfgAGdXEAfgAHAAAAAVJzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABKXNxAH4AAnEAfgAGdXEAfgAHAAAAAWJzcQB+AAJxAH4ABnVxAH4ABwAAAAF1c3EAfgACcQB+AAZ1cQB+AAcAAAABaXNxAH4AAnEAfgAGdXEAfgAHAAAAAWxzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABaXNxAH4AAnEAfgAGdXEAfgAHAAAAAW5zcQB+AAJxAH4ABnVxAH4ABwAAAAFnc3EAfgACcQB+AAZ1cQB+AAcAAAABIHNxAH4AAnEAfgAGdXEAfgAHAAAAAXBzcQB+AAJxAH4ABnVxAH4ABwAAAAFvc3EAfgACcQB+AAZ1cQB+AAcAAAABbHNxAH4AAnEAfgAGdXEAfgAHAAAAAWlzcQB+AAJxAH4ABnVxAH4ABwAAAAFjc3EAfgACcQB+AAZ1cQB+AAcAAAABeXNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAFjc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgAGdXEAfgAHAAAAAWNzcQB+AAJxAH4ABnVxAH4ABwAAAAFoc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgBIdXEAfgAHAAAAGShSZSlidWlsZGluZyBwb2xpY3kgY2FjaGVzcQB+AAJxAH4ABnVxAH4ABwAAAAFdc3EAfgACcQB+AEh1cQB+AAcAAAABXXg=";
    static final String RECORDED_UPDATES_NODETAIL =
            "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAACsdwQAAADIc3IAFGNvbS5sN3RlY2gudXRpbC5QYWlynqu2nAY3O8UCAAJMAARsZWZ0dAASTGphdmEvbGFuZy9PYmplY3Q7TAAFcmlnaHRxAH4AA3hwc3IAEWphdmEubGFuZy5Cb29sZWFuzSBygNWc+u4CAAFaAAV2YWx1ZXhwAHVyAAJbQqzzF/gGCFTgAgAAeHAAAAABNHNxAH4AAnEAfgAGdXEAfgAHAAAAAThzcQB+AAJxAH4ABnVxAH4ABwAAAAFic3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAE0c3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAAWNzcQB+AAJxAH4ABnVxAH4ABwAAAAE2c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAAWZzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABNHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFic3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATlzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABZHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAE1c3EAfgACcQB+AAZ1cQB+AAcAAAABOHNxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABM3NxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJzcQB+AAUBdXEAfgAHAAAAIDQ4YjVhNGJjNjBmZDRkYjE5MWRkZDUyNThlYWIwYTM1c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAAThzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAATlzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABOXNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAEzc3EAfgACcQB+AEh1cQB+AAcAAAANMTI4MTE1MDA5MDkwM3NxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABSXNxAH4AAnEAfgAGdXEAfgAHAAAAAU5zcQB+AAJxAH4ABnVxAH4ABwAAAAFGc3EAfgACcQB+AAZ1cQB+AAcAAAABT3NxAH4AAnEAfgBIdXEAfgAHAAAABElORk9zcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAAHNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABVnNxAH4AAnEAfgAGdXEAfgAHAAAAAWlzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABd3NxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABdXNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFpc3EAfgACcQB+AAZ1cQB+AAcAAAABdHNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABIHNxAH4AAnEAfgAGdXEAfgAHAAAAAS1zcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABU3NxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABcnNxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABVHNxAH4AAnEAfgAGdXEAfgAHAAAAAWlzcQB+AAJxAH4ABnVxAH4ABwAAAAFtc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABRnNxAH4AAnEAfgAGdXEAfgAHAAAAAXJzcQB+AAJxAH4ABnVxAH4ABwAAAAFpc3EAfgACcQB+AAZ1cQB+AAcAAAABIHNxAH4AAnEAfgAGdXEAfgAHAAAAAUFzcQB+AAJxAH4ABnVxAH4ABwAAAAF1c3EAfgACcQB+AAZ1cQB+AAcAAAABZ3NxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABNnNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABN3NxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAEzc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAFQc3EAfgACcQB+AAZ1cQB+AAcAAAABRHNxAH4AAnEAfgAGdXEAfgAHAAAAAVRzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ASHVxAH4ABwAAADtWaWV3IGF1ZGl0IGRhdGEgLSBTdGFydCBUaW1lOiBGcmkgQXVnIDA2IDE3OjAxOjMwIFBEVCAyMDEwIHNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATlzcQB+AAJxAH4ABnVxAH4ABwAAAAEyc3EAfgACcQB+AAZ1cQB+AAcAAAABLnNxAH4AAnEAfgAGdXEAfgAHAAAAATFzcQB+AAJxAH4ABnVxAH4ABwAAAAE2c3EAfgACcQB+AAZ1cQB+AAcAAAABOHNxAH4AAnEAfgAGdXEAfgAHAAAAAS5zcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATlzcQB+AAJxAH4ABnVxAH4ABwAAAAEuc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgBIdXEAfgAHAAAADTE5Mi4xNjguMTE5LjFzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABbXNxAH4AAnEAfgAGdXEAfgAHAAAAAWlzcQB+AAJxAH4ABnVxAH4ABwAAAAFuc3EAfgACcQB+AEh1cQB+AAcAAAAFYWRtaW5zcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATNzcQB+AAJxAH4ASHVxAH4ABwAAAAEzc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAEtc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgBIdXEAfgAHAAAAAi0yc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAE8c3EAfgACcQB+AAZ1cQB+AAcAAAABbnNxAH4AAnEAfgAGdXEAfgAHAAAAAW9zcQB+AAJxAH4ABnVxAH4ABwAAAAFuc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAAT5zcQB+AAJxAH4ASHVxAH4ABwAAAAY8bm9uZT5zcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ASHVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAFPc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATp4";
    static final String RECORDED_UPDATES_MESSAGE_WITH_RESPONSE =
            "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAEddwQAAAEtc3IAFGNvbS5sN3RlY2gudXRpbC5QYWlynqu2nAY3O8UCAAJMAARsZWZ0dAASTGphdmEvbGFuZy9PYmplY3Q7TAAFcmlnaHRxAH4AA3hwc3IAEWphdmEubGFuZy5Cb29sZWFuzSBygNWc+u4CAAFaAAV2YWx1ZXhwAHVyAAJbQqzzF/gGCFTgAgAAeHAAAAABNHNxAH4AAnEAfgAGdXEAfgAHAAAAAThzcQB+AAJxAH4ABnVxAH4ABwAAAAFic3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAE0c3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAAWNzcQB+AAJxAH4ABnVxAH4ABwAAAAE2c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAAWZzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABNHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFic3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATlzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABZHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAE1c3EAfgACcQB+AAZ1cQB+AAcAAAABOHNxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABM3NxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJzcQB+AAUBdXEAfgAHAAAAIDQ4YjVhNGJjNjBmZDRkYjE5MWRkZDUyNThlYWIwYTM1c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAAThzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJxAH4ABnVxAH4ABwAAAAE5c3EAfgACcQB+AAZ1cQB+AAcAAAABOXNxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAE2c3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAE4c3EAfgACcQB+AEh1cQB+AAcAAAANMTI4MTE1OTkyNjEwOHNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABV3NxAH4AAnEAfgAGdXEAfgAHAAAAAUFzcQB+AAJxAH4ABnVxAH4ABwAAAAFSc3EAfgACcQB+AAZ1cQB+AAcAAAABTnNxAH4AAnEAfgAGdXEAfgAHAAAAAUlzcQB+AAJxAH4ABnVxAH4ABwAAAAFOc3EAfgACcQB+AAZ1cQB+AAcAAAABR3NxAH4AAnEAfgBIdXEAfgAHAAAAB1dBUk5JTkdzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABc3NxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABW3NxAH4AAnEAfgAGdXEAfgAHAAAAAS9zcQB+AAJxAH4ABnVxAH4ABwAAAAF0c3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAAXNzcQB+AAJxAH4ABnVxAH4ABwAAAAF0c3EAfgACcQB+AAZ1cQB+AAcAAAABXXNxAH4AAnEAfgBIdXEAfgAHAAAADHRlc3QgWy90ZXN0XXNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABTXNxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFzc3EAfgACcQB+AAZ1cQB+AAcAAAABc3NxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAFnc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAFwc3EAfgACcQB+AAZ1cQB+AAcAAAABcnNxAH4AAnEAfgAGdXEAfgAHAAAAAW9zcQB+AAJxAH4ABnVxAH4ABwAAAAFjc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAAXNzcQB+AAJxAH4ABnVxAH4ABwAAAAFzc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABc3NxAH4AAnEAfgAGdXEAfgAHAAAAAXVzcQB+AAJxAH4ABnVxAH4ABwAAAAFjc3EAfgACcQB+AAZ1cQB+AAcAAAABY3NxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAFzc3EAfgACcQB+AAZ1cQB+AAcAAAABc3NxAH4AAnEAfgAGdXEAfgAHAAAAAWZzcQB+AAJxAH4ABnVxAH4ABwAAAAF1c3EAfgACcQB+AAZ1cQB+AAcAAAABbHNxAH4AAnEAfgAGdXEAfgAHAAAAAWxzcQB+AAJxAH4ABnVxAH4ABwAAAAF5c3EAfgACcQB+AEh1cQB+AAcAAAAeTWVzc2FnZSBwcm9jZXNzZWQgc3VjY2Vzc2Z1bGx5c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAATdzcQB+AAJxAH4ABnVxAH4ABwAAAAEuc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAAS5zcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABLnNxAH4AAnEAfgAGdXEAfgAHAAAAATFzcQB+AAJxAH4ASHVxAH4ABwAAAAkxMjcuMC4wLjFzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAEtc3EAfgACcQB+AAZ1cQB+AAcAAAABMXNxAH4AAnEAfgBIdXEAfgAHAAAAAi0xc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AEh1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAE0c3EAfgACcQB+AAZ1cQB+AAcAAAABYnNxAH4AAnEAfgAGdXEAfgAHAAAAATFzcQB+AAJxAH4ABnVxAH4ABwAAAAEzc3EAfgACcQB+AAZ1cQB+AAcAAAABY3NxAH4AAnEAfgAGdXEAfgAHAAAAAWVzcQB+AAJxAH4ABnVxAH4ABwAAAAE3c3EAfgACcQB+AAZ1cQB+AAcAAAABMnNxAH4AAnEAfgAGdXEAfgAHAAAAAS1zcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AEh1cQB+AAcAAAASMDAwMDAxMmE0YjEzY2U3Mi0xc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAE2c3EAfgACcQB+AAZ1cQB+AAcAAAABNXNxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJxAH4ABnVxAH4ABwAAAAEzc3EAfgACcQB+AAZ1cQB+AAcAAAABNnNxAH4AAnEAfgAGdXEAfgAHAAAAATBzcQB+AAJxAH4ASHVxAH4ABwAAAAY2NTUzNjBzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgBIdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgBIdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATVzcQB+AAJxAH4ASHVxAH4ABwAAAAE1c3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAABzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATxzcQB+AAJxAH4ABnVxAH4ABwAAAAFvc3EAfgACcQB+AAZ1cQB+AAcAAAABa3NxAH4AAnEAfgAGdXEAfgAHAAAAAS9zcQB+AAJxAH4ABnVxAH4ABwAAAAE+c3EAfgACcQB+AEh1cQB+AAcAAAAFPG9rLz5zcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAATJzcQB+AAJxAH4ABnVxAH4ABwAAAAEwc3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgBIdXEAfgAHAAAAAzIwMHNxAH4AAnEAfgAGdXEAfgAHAAAAATpzcQB+AAJxAH4ASHVxAH4ABwAAAAE6c3EAfgACcQB+AAZ1cQB+AAcAAAABMHNxAH4AAnEAfgBIdXEAfgAHAAAAATBzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAVtzcQB+AAJxAH4ASHVxAH4ABwAAAAFbc3EAfgACcQB+AAZ1cQB+AAcAAAABLXNxAH4AAnEAfgAGdXEAfgAHAAAAATRzcQB+AAJxAH4ASHVxAH4ABwAAAAItNHNxAH4AAnEAfgAGdXEAfgAHAAAAAVxzcQB+AAJxAH4ASHVxAH4ABwAAAAFcc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAFkc3EAfgACcQB+AAZ1cQB+AAcAAAABZXNxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAFhc3EAfgACcQB+AAZ1cQB+AAcAAAABaXNxAH4AAnEAfgAGdXEAfgAHAAAAAWxzcQB+AAJxAH4ABnVxAH4ABwAAAAExc3EAfgACcQB+AEh1cQB+AAcAAAAHZGV0YWlsMXNxAH4AAnEAfgAGdXEAfgAHAAAAASxzcQB+AAJxAH4ASHVxAH4ABwAAAAEsc3EAfgACcQB+AAZ1cQB+AAcAAAABLXNxAH4AAnEAfgAGdXEAfgAHAAAAATRzcQB+AAJxAH4ASHVxAH4ABwAAAAItNHNxAH4AAnEAfgAGdXEAfgAHAAAAAVxzcQB+AAJxAH4ASHVxAH4ABwAAAAFcc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgBIdXEAfgAHAAAAATpzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABdnNxAH4AAnEAfgAGdXEAfgAHAAAAAWlzcQB+AAJxAH4ABnVxAH4ABwAAAAFsc3EAfgACcQB+AAZ1cQB+AAcAAAABIHNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABdHNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAFpc3EAfgACcQB+AAZ1cQB+AAcAAAABbHNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAF3c3EAfgACcQB+AAZ1cQB+AAcAAAABaXNxAH4AAnEAfgAGdXEAfgAHAAAAAXRzcQB+AAJxAH4ABnVxAH4ABwAAAAFoc3EAfgACcQB+AAZ1cQB+AAcAAAABIHNxAH4AAnEAfgAGdXEAfgAHAAAAAWNzcQB+AAJxAH4ABnVxAH4ABwAAAAFvc3EAfgACcQB+AAZ1cQB+AAcAAAABbHNxAH4AAnEAfgAGdXEAfgAHAAAAAW9zcQB+AAJxAH4ABnVxAH4ABwAAAAFuc3EAfgACcQB+AAZ1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgAGdXEAfgAHAAAAAWxzcQB+AAJxAH4ABnVxAH4ABwAAAAFzc3EAfgACcQB+AAZ1cQB+AAcAAAABb3NxAH4AAnEAfgAGdXEAfgAHAAAAASxzcQB+AAJxAH4ABnVxAH4ABwAAAAEgc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgAGdXEAfgAHAAAAASBzcQB+AAJxAH4ABnVxAH4ABwAAAAFjc3EAfgACcQB+AAZ1cQB+AAcAAAABb3NxAH4AAnEAfgAGdXEAfgAHAAAAAW1zcQB+AAJxAH4ABnVxAH4ABwAAAAFtc3EAfgACcQB+AAZ1cQB+AAcAAAABYXNxAH4AAnEAfgBIdXEAfgAHAAAAJmV2aWwgZGV0YWlsIHdpdGggY29sb246ICBhbHNvLCBhIGNvbW1hc3EAfgACcQB+AAZ1cQB+AAcAAAABLHNxAH4AAnEAfgBIdXEAfgAHAAAAASxzcQB+AAJxAH4ABnVxAH4ABwAAAAEtc3EAfgACcQB+AAZ1cQB+AAcAAAABNHNxAH4AAnEAfgBIdXEAfgAHAAAAAi00c3EAfgACcQB+AAZ1cQB+AAcAAAABXHNxAH4AAnEAfgBIdXEAfgAHAAAAAVxzcQB+AAJxAH4ABnVxAH4ABwAAAAE6c3EAfgACcQB+AEh1cQB+AAcAAAABOnNxAH4AAnEAfgAGdXEAfgAHAAAAAWRzcQB+AAJxAH4ABnVxAH4ABwAAAAFlc3EAfgACcQB+AAZ1cQB+AAcAAAABdHNxAH4AAnEAfgAGdXEAfgAHAAAAAWFzcQB+AAJxAH4ABnVxAH4ABwAAAAFpc3EAfgACcQB+AAZ1cQB+AAcAAAABbHNxAH4AAnEAfgAGdXEAfgAHAAAAATNzcQB+AAJxAH4ASHVxAH4ABwAAAAdkZXRhaWwzc3EAfgACcQB+AAZ1cQB+AAcAAAABXXNxAH4AAnEAfgBIdXEAfgAHAAAAAV14";
}
