package com.l7tech.server.event.system;

import java.util.logging.Level;

import com.l7tech.gateway.common.Component;

/**
 * Event generated by the admin web service.
 *
 * @author $Author$
 * @version $Revision$
 */
public class AdminWebServiceEvent extends SystemEvent {

    //- PUBLIC

    public AdminWebServiceEvent(
            Object source,
            Level level,
            String ip,
            String message,
            long identityProviderOid,
            String userName,
            String userId) {
        super(source, Component.GW_ADMINWS, ip, level, message, identityProviderOid, userName, userId);
    }

    public String getAction() {
        return NAME;
    }

    //- PRIVATE

    private static final String NAME = "Admin Web Service Request";
}
