/*
 * StockQuoteFrame.java
 *
 * Created on July 31, 2003, 11:12 AM
 */

package com.l7tech.test;

import javax.swing.tree.*;

/**
 *
 * @author  alex
 */
public class StockQuoteFrame extends javax.swing.JFrame {
    /** Creates new form StockQuoteFrame */
    public StockQuoteFrame() {
        MutableTreeNode root = new DefaultMutableTreeNode( "Root" );
        MutableTreeNode stocksNode = new DefaultMutableTreeNode( "Stocks" );
        MutableTreeNode bondsNode = new DefaultMutableTreeNode( "Bonds" );
        MutableTreeNode fundsNode = new DefaultMutableTreeNode( "Mutual Funds" );
        root.insert( stocksNode, 0 );
        root.insert( bondsNode, 1 );
        root.insert( fundsNode, 2 );
        
        _treeModel = new DefaultTreeModel(root);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        centerPanel = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        tree = new javax.swing.JTree();
        rightPanel = new javax.swing.JPanel();
        middleToolbar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        rightSplit = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextPane1 = new javax.swing.JTextPane();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        toolbar = new javax.swing.JToolBar();
        toolButton1 = new javax.swing.JButton();
        toolButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileExitItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewRefreshItem = new javax.swing.JMenuItem();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        centerPanel.setLayout(new java.awt.BorderLayout());

        tree.setModel(_treeModel);
        tree.setRootVisible(false);
        splitPane.setLeftComponent(tree);

        rightPanel.setLayout(new java.awt.BorderLayout());

        middleToolbar.setBorder(new javax.swing.border.EtchedBorder());
        middleToolbar.setFloatable(false);
        middleToolbar.setOrientation(1);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/l7tech/console/resources/Add16.gif")));
        jButton1.setToolTipText("Add to Chart");
        middleToolbar.add(jButton1);

        rightPanel.add(middleToolbar, java.awt.BorderLayout.WEST);

        rightSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Symbol", "Name", "Quantity", "Purchase Price", "Market Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        rightSplit.setLeftComponent(jScrollPane1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.add(jTextPane1, java.awt.BorderLayout.CENTER);

        rightSplit.setRightComponent(jPanel1);

        rightPanel.add(rightSplit, java.awt.BorderLayout.CENTER);

        splitPane.setRightComponent(rightPanel);

        centerPanel.add(splitPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        statusPanel.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("Status");
        statusLabel.setBorder(new javax.swing.border.EtchedBorder());
        statusPanel.add(statusLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(statusPanel, java.awt.BorderLayout.SOUTH);

        toolButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/l7tech/console/resources/New16.gif")));
        toolbar.add(toolButton1);

        toolButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/l7tech/console/resources/Refresh16.gif")));
        toolbar.add(toolButton2);

        getContentPane().add(toolbar, java.awt.BorderLayout.NORTH);

        fileMenu.setText("File");
        fileExitItem.setMnemonic('x');
        fileExitItem.setText("Exit");
        fileExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitItemActionPerformed(evt);
            }
        });

        fileMenu.add(fileExitItem);

        menuBar.add(fileMenu);

        viewMenu.setText("View");
        viewRefreshItem.setText("Refresh");
        viewMenu.add(viewRefreshItem);

        menuBar.add(viewMenu);

        setJMenuBar(menuBar);

        pack();
    }//GEN-END:initComponents

    private void fileExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitItemActionPerformed
        hide();
        dispose();
        System.exit(0);
    }//GEN-LAST:event_fileExitItemActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new StockQuoteFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JMenuItem fileExitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JToolBar middleToolbar;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane rightSplit;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton toolButton1;
    private javax.swing.JButton toolButton2;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JTree tree;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem viewRefreshItem;
    // End of variables declaration//GEN-END:variables
    
    protected TreeModel _treeModel;
}
