#!/bin/bash
#
# Routing script for the Secure Span Gateway Server
#
# chkconfig: - 99 01
# description: Layer7's Secure Span Gateway Routes

# Source function library.
. /etc/rc.d/init.d/functions
# source config
. /etc/SSG_INSTALL

if [ -n $net_back_ip ]; then
	exit
else 
	

route=/sbin/route

start() {
	# Add back end routes
	# 
	$route add -net $net_back_net netmask $net_back_mask gw $net_back_rt
	$route add -net 224.0.0.0 netmask 240.0.0.0 dev eth0
}
stop() {
	$route del -net $net_back_net netmask $net_back_mask gw $net_back_rt
	$route del -net 224.0.0.0 netmask 240.0.0.0 dev eth0
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
esac

exit 

