#!/bin/bash
#
# Startup script for the Secure Span Gateway Server
#
# chkconfig: - 99 01
# description: Layer7's Secure Span Gateway Daemon \
#	       secures and provides access for SOAP services
# processname: tomcat
# pidfile: /var/run/ssg.pid
# config: /ssg/tomcat

# Source function library.
. /etc/rc.d/init.d/functions

if [ -z "$TOMCAT_HOME" ]; then 
	TOMCAT_HOME="/ssg/tomcat/"
	echo "Setting TOMCAT_HOME to /ssg/tomcat"
fi

ssg="$TOMCAT_HOME/bin/catalina.sh"

ssguser="gateway"
prog="ssg"

# The semantics of these two functions differ from the way apachectl does
# things -- attempting to start while running is a failure, and shutdown
# when not running is also a failure.  So we just do it the way init scripts
# are expected to behave here.
start() {
        echo -n $"Starting $prog: "
        su - $ssguser -c "$ssg start -security"
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch /var/lock/subsys/ssg
        return $RETVAL
}
stop() {
	echo -n $"Stopping $prog: "
	su - $ssguser -c "$ssg stop "
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/ssg /var/run/ssg.pid
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
esac

exit $RETVAL
