#!/bin/bash
#
# Utility for Secure Span Gateway Server system configuration
#
# chkconfig: - 99 01
# description: Layer7's Secure Span Gateway System Configuration Utility

# Source function library.

if [ -z "$SSGHOME" ]; then
	SSGHOME="/ssg/"
fi

ssgconfigutil="perl $SSGHOME/sysconfigwizard/ssg_sys_config.pl"

message="Applying Network Configuration"
tries=3
count=0
USER=`whoami`

# This script redirects STDOUT and STDERR to /dev/null as well as closing STDIN (<&-) so it can be detached from a
# terminal

start() {
	echo -n $"$message: "
	if [ "$USER" = "root" ]; then
        	${ssgconfigutil} &>/dev/null <&-
        	RETVAL=$?
	else
		echo "Need to be root or $ssguser to run this script";
		exit
	fi

    echo
    # [ $RETVAL = 0 ] && touch /var/lock/subsys/ssg
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart)
	;;
esac

exit $RETVAL
