#!/bin/sh
. /opt/SecureSpan/Appliance/libexec/envclean

if [ "$(whoami)" = "layer7" ] || [ "$(whoami)" = "root" ] ; then
    exec sudo -u gateway $0 "$@"
else
    exec /opt/SecureSpan/Gateway/runtime/bin/gateway.sh "${@}"
fi
