#!/bin/sh
unset PATH

if [ z$1z != zreallyForSurez ]; then
    /bin/echo 'Confirmation argument not present -- aborted' 1>&2
    exit 3;
fi

cd /var/opt/sun/sca6000/keydata || exit 1

# This must be the very last line in the file
/bin/tar xzf -
