#!/bin/bash
#
# Utility for Secure Span Gateway Server system configuration
#
# chkconfig: 2345 09 91
# description: Layer7's Secure Span Gateway System Configuration Utility

if [ -z "$SSGHOME" ]; then
	SSGHOME="/opt/SecureSpan/Gateway"
fi                           

ssgconfigutil="/usr/bin/perl /opt/SecureSpan/Appliance/config/ssg_sys_config.pl"
migrationdeamon="${SSGHOME}/config/backup/ssgrestore.sh cfgdeamon"
authconfigfile="/opt/SecureSpan/Appliance/config/configfiles/radius_ldap_setup.conf"
authenticationconfigutil="/bin/bash /opt/SecureSpan/Appliance/config/authconfig/radius_ldap_setup.sh --configfile ${authconfigfile}"

MESSAGE="Applying Network (Re)Configuration"
USER=`whoami`

# This script redirects STDOUT and STDERR to /dev/null as well as closing STDIN (<&-) so it can be detached from a
# terminal

start() {
	if [ "$USER" = "root" ]; then
		echo "${MESSAGE}: "
        (${ssgconfigutil})
        RETVAL=$?
        # plugin of migration utility copying system files at the right place
        (${migrationdeamon})

        #run the authentication configuration script which reads litter files as well.
        if [ -e ${authconfigfile} ] ; then
            (${authenticationconfigutil})
        fi
	else
		echo "Need to be root to run this script";
		exit
	fi

    echo
    return $RETVAL
}

# See how we were called. Run this on both start and stop since this is a run and terminate script
case "$1" in
  start)
	start
	;;
  stop)
    start
	;;
  config)
    start
	;;
  restart)
	;;
esac

exit $RETVAL
