#!/bin/sh -x 
echo "Layer 7 SecureSpan(tm) Gateway v4.0" >/etc/issue

# Startups
cd /etc/rc3.d
# Network config
ln -sf ../init.d/ssg_tcp_tune.sh S71SSG_tcptune
# SSG startup
ln -sf ../init.d/ssg S99SSG_ssg
# shutdowns:
cd /etc/rc0.d
# run network config on shutdown
ln -s ../init.d/ssg-sysconfig K03SSG_sysconfig
# and shut down the ssg nicely
ln -sf ../init.d/ssg K04SSG_ssg

cd /ssg

# migrate the structure to the new partitioning scheme using the configuration wizard
# Set java in version, in case its needed
JAVA_HOME=/usr/j2se/jdk1.6.0_01
export JAVA_HOME

/ssg/configwizard/ssgconfig.sh -partitionMigrate 

# Added user previously, pre-expire them
passwd -x 0 ssgconfig

# set the ssgconfig password, this string was copied from a /etc/shadow of a machine
# where the ssgconfig password was previously set to '7layer'. Salting may apply.
PASSWD=YyodXLOqlkTSg

tmpfile=/etc/shadow.orig$$
#create a temporary input file
cp /etc/shadow ${tmpfile}

nawk -F: '{
	if ( $1 == "ssgconfig" )
		printf"%s:%s:%s:%s:%s:%s:%s:%s:%s\n",$1,passwd,$3,$4,$5,$6,$7,$8,$9
	else
		printf"%s:%s:%s:%s:%s:%s:%s:%s:%s\n",$1,$2,$3,$4,$5,$6,$7,$8,$9
}' passwd="$PASSWD" ${tmpfile} > /etc/shadow
if [ `grep $PASSWD /etc/shadow` ]; then
	# passwd changed
	echo "Password set for ssgconfig"
fi

rm -f ${tmpfile}

# Enable ipfilter, you are at risk of being disconnected...
/usr/sbin/svcadm enable -r network/ipfilter
