#!/bin/sh

# Detect existing user/group ids
if [ -d /ssg ] ; then
    UID_GATEWAY=`[ -d /ssg ] && ls -nd /ssg | awk '{print $3}'`
    GID_GATEWAY=`[ -d /ssg ] && ls -nd /ssg | awk '{print $4}'`
    UID_SSGCONF=`[ -f /ssg/configwizard/ssgconfig0.log ] && ls -nd /ssg/configwizard/ssgconfig0.log | awk '{print $3}'`
    UID_LAYER7=""
    GID_LAYER7=""
else
    UID_GATEWAY=`[ -d /opt/SecureSpan/Gateway ] && ls -nd /opt/SecureSpan/Gateway | awk '{print $3}'`
    GID_GATEWAY=`[ -d /opt/SecureSpan/Gateway ] && ls -nd /opt/SecureSpan/Gateway | awk '{print $4}'`
    UID_SSGCONF="";
    UID_LAYER7=`[ -f /opt/SecureSpan/Gateway/config/config.log ] && ls -nd /opt/SecureSpan/Gateway/config/config.log | awk '{print $3}'`
    GID_LAYER7=`[ -f /opt/SecureSpan/Gateway/config/config.log ] && ls -nd /opt/SecureSpan/Gateway/config/config.log | awk '{print $4}'`
fi

if [ "$UID_GATEWAY" = "$UID_SSGCONF" ] ; then
    UID_SSGCONF=""
fi

GWGROUPFOUND=`grep \^gateway\: /etc/group`
if [ -n "${GWGROUPFOUND}" ]; then
	echo "group gateway already exists"
else
	echo "adding gateway group"
    GID_PARAM=""
    if [ $GID_GATEWAY ] ; then
        GID_PARAM="-g $GID_GATEWAY"
    fi
	groupadd $GID_PARAM gateway
        if [ ${?} -eq 1 ]; then
                echo "Error: Group gateway failed to add"
                exit 1;
	fi
fi

GWUSERFOUND=`grep \^gateway\: /etc/passwd`
if [ -n "${GWUSERFOUND}" ]; then
	echo "user gateway already exists"
else
    UID_PARAM=""
    if [ $UID_GATEWAY ] ; then
        UID_PARAM="-u $UID_GATEWAY"
    fi
	echo "adding gateway user"
	useradd $UID_PARAM -G gateway -g gateway -d /export/home/gateway -s /usr/bin/bash gateway
        if [ ${?} -eq 1 ]; then
                echo "Error: User gateway failed to add"
                exit 1;
	fi
fi

L7GROUPFOUND=`grep \^layer7\: /etc/group`
if [ -n "${L7GROUPFOUND}" ]; then
	echo "group layer7 already exists"
else
	echo "adding layer7 group"
    GID_PARAM=""
    if [ $GID_LAYER7 ] ; then
        GID_PARAM="-g $GID_LAYER7"
    fi
	groupadd $GID_PARAM layer7
        if [ ${?} -eq 1 ]; then
                echo "Error: Group layer7 failed to add"
                exit 1;
	fi
fi

L7USERFOUND=`grep \^layer7\: /etc/passwd`
if [ -n "${L7USERFOUND}" ]; then
	echo "user layer7 already exists"
else
	echo "adding layer7 user"
    UID_PARAM=""
    if [ $UID_LAYER7 ] ; then
        UID_PARAM="-u $UID_LAYER7"
    fi
	useradd $UID_PARAM -G gateway -g gateway -d /export/home/layer7 -s /usr/bin/bash layer7
        if [ ${?} -eq 1 ]; then
                echo "Error: User layer7 failed to add"
                exit 1;
	fi
fi

echo "SSG Users and Group check: Success"
exit 0
