#!/bin/bash

if [ `grep ^gateway: /etc/group` ]; then
	echo "group gateway already exists"
else
	echo "adding gateway group"
	groupadd gateway
fi

if [ `grep ^gateway: /etc/passwd` ]; then
	echo "user gateway already exists"
else
	echo "adding gateway user"
	useradd -G gateway -d /export/home/gateway -s /usr/bin/bash gateway
fi

if [ `grep ^ssgconfig: /etc/passwd` ]; then
	echo "user ssgconfig already exists"
else
	echo "adding ssgconfig user, useradd will whine, this is safe to ignore"
	useradd -G gateway -d /export/home/ssgconfig -s /usr/bin/bash ssgconfig
fi

exit 0
