#!/bin/sh

#Because I just don't care how nicely it dies, just that it's dead. Really dead.
/etc/init.d/ssg reallystop

userdel -r gateway
if [ ${?} -eq 1 ]; then
	usedel gateway
	# handle the dir not being there
fi
userdel -r ssgconfig
if [ ${?} -eq 1 ]; then
	usedel ssgconfig
	# handle the dir not being there, just in case
fi
groupdel gateway

