#!/bin/sh

#Stop the ssg
[ -f /etc/init.d/ssg ] && /etc/init.d/ssg stop

userdel -r gateway
if [ ${?} -eq 1 ]; then
	userdel gateway
	# handle the dir not being there
fi
userdel -r ssgconfig
if [ ${?} -eq 1 ]; then
	userdel ssgconfig
	# handle the dir not being there, just in case
fi
groupdel gateway

exit 0
