#!/bin/sh

userdel -r gateway
if [ ${?} -eq 1 ]; then
	userdel gateway
	# handle the dir not being there
fi
userdel -r layer7
if [ ${?} -eq 1 ]; then
	userdel layer7
	# handle the dir not being there, just in case
fi
groupdel gateway
groupdel layer7

exit 0
