#!/bin/bash
#
# Startup script for the SecureSpan Enterprise Manager
#
# chkconfig: - 99 01
# description: Layer 7 SecureSpan Enterprise Manager Daemon
# processname: ssemd

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
USER=$(whoami)
if [ $USER != "root" ] ; then
    echo "Need to be root to run this script";
    exit
fi

# Config
PID_FILE="ssemd"
EM_USER="ssem"
EM_SCRIPT="/opt/SecureSpan/EnterpriseManager/bin/enterprisemanager.sh"
EMDB_PATH="/opt/SecureSpan/EnterpriseManager/var/db/emsdb"
EMDB_GROUP="layer7"

start() {
        if [ ! -x "${EM_SCRIPT}" ] ; then
            echo "Service script not found or not executable."
            exit 5
        fi

        echo -n $"Starting Enterprise Manager: "
        daemon --check "${PID_FILE}" "${EM_SCRIPT}" "${EM_USER}" "/var/run/${PID_FILE}.pid"
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/ssemd
        return $RETVAL
}

stop() {
        echo -n $"Shutting down Enterprise Manager: "
        killproc "${PID_FILE}"
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/ssemd

        if [ ! -z "${EMDB_GROUP}" ] && [ -d "${EMDB_PATH}" ] ; then
            chown -R "${EM_USER}.${EMDB_GROUP}" "${EMDB_PATH}"
            chmod g+w -R "${EMDB_PATH}"
        fi

        return $RETVAL
}

status() {
        if [ -f "/var/run/${PID_FILE}.pid" ] ; then
            PID=$(<"/var/run/${PID_FILE}.pid")
            if [ ! -z "${PID}" ] && [ -d "/proc/${PID}" ] ; then
                echo "Enterprise Manager (pid $PID) is running..."
                return 0
            else
                echo "Enterprise Manager dead but pid file exists"
                return 1
            fi
        else
            echo "Enterprise Manager is stopped"
            return 3
        fi
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
        sleep 5
	start
	;;
  status)
        status ssemd
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit $RETVAL
