#!/bin/sh

MODULE="$1"

# Pull in collector support functions
. "${COLLECTOR_HOME}"/collectorlib

preModule "$MODULE"

#Define and create output folders
JAVA_OUTPUT_DIR="${BASE_OUTPUT_DIR}/${MODULE}"
mkdir -p "${JAVA_OUTPUT_DIR}"

if [ -w "${JAVA_OUTPUT_DIR}" ]
then
    logAndRunCmd "/opt/SecureSpan/JDK/bin/java -version &> \"${JAVA_OUTPUT_DIR}\"/java_version.txt"
    logAndRunCmd "ls -l /opt/SecureSpan/JDK/jre/lib/ext &> \"${JAVA_OUTPUT_DIR}\"/jre_lib_ext.txt"
    logAndRunCmd "cp /opt/SecureSpan/JDK/jre/lib/security/java.security \"${JAVA_OUTPUT_DIR}\""
else
    echo "Could not create java module directory."
fi

postModule "$MODULE"
