#!/bin/sh

MODULE=$1

# Pull in collector support functions
#
. ${COLLECTOR_HOME}/collectorlib

preModule $MODULE

#Define and create output folders
JAVA_MODULE_BaseOutputDirectory=${ALL_MODULES_BASE_OUTPUT_DIR}/${MODULE}
JAVA_MODULE_BaseOutputDirectory_config=${JAVA_MODULE_BaseOutputDirectory}/config
JAVA_MODULE_BaseOutputDirectory_logs=${JAVA_MODULE_BaseOutputDirectory}/logs
mkdir -p ${JAVA_MODULE_BaseOutputDirectory}
#mkdir -p ${JAVA_MODULE_BaseOutputDirectory_config}
#mkdir -p ${JAVA_MODULE_BaseOutputDirectory_logs}


logCommand /opt/SecureSpan/JDK/bin/java -version
/opt/SecureSpan/JDK/bin/java -version 2> ${JAVA_MODULE_BaseOutputDirectory}/java_version.txt

logCommand ls /opt/SecureSpan/JDK/jre/lib/ext
ls -l /opt/SecureSpan/JDK/jre/lib/ext > ${JAVA_MODULE_BaseOutputDirectory}/jre_lib_ext.txt

logCommand cat /opt/SecureSpan/JDK/jre/lib/security/java.security
cp /opt/SecureSpan/JDK/jre/lib/security/java.security ${JAVA_MODULE_BaseOutputDirectory}

postModule $MODULE
