#!/bin/sh

MODULE="$1"

# Pull in collector support functions
. "${COLLECTOR_HOME}"/collectorlib

preModule "$MODULE"

#Define and create output folders
MONITOR_OUTPUT_DIR="${BASE_OUTPUT_DIR}/${MODULE}"
mkdir -p "${MONITOR_OUTPUT_DIR}"

if [ -w "${MONITOR_OUTPUT_DIR}" ]
then
    logAndRunCmd "ps axjf &> \"${MONITOR_OUTPUT_DIR}\"/ps_axjf.txt"
    logAndRunCmd "vmstat 1 30 &>> \"${MONITOR_OUTPUT_DIR}\"/vmstat_1_30.txt"
    logAndRunCmd "timeout 30s netstat -i 1 &>> \"${MONITOR_OUTPUT_DIR}\"/netstat_1_30.txt"
    logAndRunCmd "ps auxwww | grep gateway &> \"${MONITOR_OUTPUT_DIR}\"/ps_auxwww.txt"
else
    echo "Unable to create monitor output directory."
fi

postModule "$MODULE"
