#!/bin/sh

MODULE="$1"
# Pull in collector support functions
. "${COLLECTOR_HOME}"/collectorlib
#Define and create output folders
OS_DIR="${BASE_OUTPUT_DIR}/${MODULE}"

preModule "$MODULE"
mkdir -p "${OS_DIR}"

if [ -w "${OS_DIR}" ]
then
    #Begin data collection
    logAndRunCmd "uname -a &> \"${OS_DIR}\"/uname.txt"
    logAndRunCmd "cat /etc/redhat-release &> \"${OS_DIR}\"/redhat-release.txt"
    #list system services at runlevel
    logAndRunCmd "chkconfig --list &> \"${OS_DIR}\"/chkconfig-list.txt"
    logAndRunCmd "rpm -qa &> \"${OS_DIR}\"/rpmList.txt"
    logAndRunCmd "cp /var/log/messages* \"${OS_DIR}"\"
    logAndRunCmd "who -r &> \"${OS_DIR}\"/who-runlevel.txt"
    logAndRunCmd "dmesg &> \"${OS_DIR}\"/dmesg.txt"
    logAndRunCmd "cp /etc/ntp.conf \"${OS_DIR}\""
    logAndRunCmd "ntpq -p &> \"${OS_DIR}\"/ntpq-peers.txt"
    logAndRunCmd "cp /etc/security/limits.conf \"${OS_DIR}\""
    logAndRunCmd "cp /etc/security/limits.d/*ssg* \"${OS_DIR}\""
    logAndRunCmd "whoami &> \"${OS_DIR}\"/who-am-i.txt"
    #view all soft limits
    logAndRunCmd "su -c \"ulimit -S -a\" -s /bin/sh gateway &>> \"${OS_DIR}\"/ulimit-soft.txt"
    #view all hard limits
    logAndRunCmd "su -c \"ulimit -H -a\" -s /bin/sh gateway &>> \"${OS_DIR}\"/ulimit-hard.txt"
    logAndRunCmd "cp /var/log/bash_commands.log \"${OS_DIR}\""
    logAndRunCmd "top -b -n 1 &> \"${OS_DIR}\"/top.txt"
else
    echo "Unable to create os output directory"
fi

postModule "$MODULE"