#!/bin/sh

MODULE=$1
LEVEL=$2

VMWARE_CMDDIR=/usr/sbin

# Pull in collector support functions
#
. ${COLLECTOR_HOME}/collectorlib

preModule $MODULE

if [ -x ${VMWARE_CMDDIR}/vmware-checkvm ]
then
    logCommand vmware-checkvm
    vmware-checkvm

    logCommand vmware-checkvm -hp
    vmware-checkvm -hp

    logCommand vmware-toolbox-cmd stat balloon
    vmware-toolbox-cmd stat balloon

    logCommand vmware-toolbox-cmd stat memlimit
    vmware-toolbox-cmd stat memlimit

    logCommand vmware-toolbox-cmd stat memres
    vmware-toolbox-cmd stat memres

    logCommand vmware-toolbox-cmd stat cpures
    vmware-toolbox-cmd stat cpures

    logCommand vmware-toolbox-cmd stat cpulimit
    vmware-toolbox-cmd stat cpulimit

    logCommand vmware-toolbox-cmd timesync status
    vmware-toolbox-cmd timesync status
else
  echo "Error: vmware-checkvm command missing, likely not a virtual machine"
fi


postModule $MODULE
