#!/bin/sh

MODULE=$1
LEVEL=$2

VMWARE_CMDDIR=/usr/sbin

# Pull in collector support functions
. ${COLLECTOR_HOME}/collectorlib

preModule $MODULE


#Define and create output folders
VMWARE_MODULE_BaseOutputDirectory=${ALL_MODULES_BaseOutputDirectory}/${MODULE}
VMWARE_MODULE_BaseOutputDirectory_config=${VMWARE_MODULE_BaseOutputDirectory}/config
VMWARE_MODULE_BaseOutputDirectory_logs=${VMWARE_MODULE_BaseOutputDirectory}/logs
mkdir -p ${VMWARE_MODULE_BaseOutputDirectory}
#mkdir -p ${VMWARE_MODULE_BaseOutputDirectory_config}
#mkdir -p ${VMWARE_MODULE_BaseOutputDirectory_logs}

#Begin data collection
if [ -x ${VMWARE_CMDDIR}/vmware-checkvm ]
then
    logCommand vmware-checkvm
    vmware-checkvm > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-checkvm.txt

    logCommand vmware-checkvm -hp
    vmware-checkvm -hp > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-checkvm-hp.txt

    logCommand vmware-toolbox-cmd stat balloon
    vmware-toolbox-cmd stat balloon > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-toolbox-cmd-stat-balloon.txt

    logCommand vmware-toolbox-cmd stat memlimit
    vmware-toolbox-cmd stat memlimit > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-toolbox-cmd-stat-memlimit.txt

    logCommand vmware-toolbox-cmd stat memres
    vmware-toolbox-cmd stat memres > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-toolbox-cmd-stat-memres.txt

    logCommand vmware-toolbox-cmd stat cpures
    vmware-toolbox-cmd stat cpures > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-toolbox-cmd-stat-cpures.txt

    logCommand vmware-toolbox-cmd stat cpulimit
    vmware-toolbox-cmd stat cpulimit > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-toolbox-cmd-stat-cpulimit.txt

    logCommand vmware-toolbox-cmd timesync status
    vmware-toolbox-cmd timesync status > ${VMWARE_MODULE_BaseOutputDirectory}/vmware-toolbox-cmd-timesync-status.txt
else
  echo "Error: vmware-checkvm command missing, likely not a virtual machine"
fi

#
#if [ $LEVEL -ge $DETAIL ]
#then
#    #nothing here
#fi
#
#if [ $LEVEL -ge $EVERYTHING ]
#then
#    #nothing here
#fi

postModule $MODULE
