#!/bin/bash
#
# Utility for Secure Span Gateway Server system configuration
#
# chkconfig: 2345 09 91
# description: Layer7's Secure Span Gateway System Configuration Utility

# startup is complicated by the fact that 
# there's no user in the /etc/init run at startup
# on Solaris only
MESSAGE="Applying Network (Re)Configuration"
if [ "${_INIT_RUN_LEVEL}" = 3  -o "${_INIT_RUN_LEVEL}" = 6  -o "$LOGNAME" = "root" ] ; then
    # its either startup, shutdown, or run interactively by root
    echo "${MESSAGE}"
else 
    echo "Must be root to run this script"
    exit
fi


if [ -z "$SSGHOME" ]; then
	SSGHOME="/ssg"
fi

ssgconfigutil="/usr/bin/perl ${SSGHOME}/sysconfigwizard/ssg_sys_config.pl"
migrationdeamon="${SSGHOME}/migration/ssgmigration.sh cfgdeamon"


# This script redirects STDOUT and STDERR to /dev/null as well as closing STDIN (<&-) so it can be detached from a
# terminal

start() {
        (${ssgconfigutil})
        RETVAL=$?
        # plugin of migration utility copying system files at the right place
        (${migrationdeamon})
    	echo
    	return $RETVAL
}

# See how we were called. Run this on both start and stop since this is a run and terminate script
case "$1" in
  start)
	start
	;;
  stop)
    start
	;;
  config)
    start
	;;
  restart)
	;;
esac

exit $RETVAL
