package com.l7tech.kerberos;

import com.l7tech.util.*;
import org.bouncycastle.asn1.*;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Created by balro10 on 2016-08-18.
 */

/*
 * Implementation of KRB5_AP_REQ ticket parsing
 *
 * The JDK implements parsing but only as part of authentication of the ticket.
 * It is not possible in the JDK to peek into the KRB5_AP_REQ ticket without authenticating
 * it.
 *
 * This class parses the non-encrypted portions of the tickets so they can be examined prior
 * to authentication.
 *
 *
 *
 *
 */


// SSG-13640 - When the SSG has multiple service keys (SPNs) in its keytab it attempts to:
//     guess the SPN required to authenticate the via in the bound URL (KerberosUtils.extractSpnFromRequest())
//     or by reverse lookup the remote calling endpoint and do the same (to support Load Balancer Proxies)
//     or failing those uses the first key in the keytab.
//     This class supports the parsing of the plaintext portion of the inbound ticket so that the SPN
//     can be obtained before the Gateway needs to know which SPN to authenticate the request with.


public class Krb5ApReq {
    private static final Logger LOGGER = Logger.getLogger(Krb5ApReq.class.getName());

    public static final Config config = ConfigFactory.getCachedConfig();

    public static final String GSSAPI_TOKEN_OID = "1.2.840.113554.1.2.2";
    public static final int GSSAPI_APP_ID = 0;
    public static final int KRB5_APREQ_ID = 14;
    public static final int KRB5_TICKET_ID = 1;

    private String protocol;
    private String host;
    private String realm;

    // Constructor expects GSSAPI Wrapped as byte array
    public Krb5ApReq(byte[] possiblyKerberosToken) {

        if (JdkLoggerConfigurator.debugState() ) {
            LOGGER.warning("Decoding Ticket: " + HexUtils.encodeBase64(possiblyKerberosToken));
        }

        /*
         * Bug fix DE340275: If the ticket contains SPNEGO wrapper, remove the wrapper and then parse the
         * the Kerberos V5 token. If "com.l7tech.kerberos.useSpnFromInboundTicket" is set to TRUE, the SPN
         * is generated by parsing the Kerberos V5 token.
         */
        byte[] ticket = removeSPNEGOWrapperIfExists(possiblyKerberosToken);

        verifyAndParse(ticket);

        if (JdkLoggerConfigurator.debugState() ) {
            LOGGER.warning("Decoded protocol: " + protocol +", host: " + host + ", realm: " + realm );
        }
    }

    private void verifyAndParse(byte[] ticket) {
        ASN1InputStream ain= null;
        ASN1InputStream wrappedStream = null;
        ASN1InputStream apReqStream = null;
        ASN1InputStream innerTicketStream = null;

        try {
            ain = new ASN1InputStream(ticket);
            final DERApplicationSpecific gssApiWrap = (DERApplicationSpecific) ain.readObject();

            if ( ! (gssApiWrap.isConstructed() && gssApiWrap.getApplicationTag() == GSSAPI_APP_ID ) ) {
                throw new Krb5ApReqException();
            }

            byte[] gssapiContents = gssApiWrap.getContents();
            wrappedStream = new ASN1InputStream(gssapiContents);
            ASN1ObjectIdentifier gssapioid = ASN1ObjectIdentifier.getInstance(wrappedStream.readObject());

            if ( gssapioid == null || gssapiContents == null  || ! gssapioid.toString().equals(GSSAPI_TOKEN_OID) ) {
                throw new Krb5ApReqException();
            }

            final int tag = (wrappedStream.read() << 8) | wrappedStream.read();
            if ( tag != 0x100 ) {
                throw new Krb5ApReqException();
            }

            DERApplicationSpecific apReq = (DERApplicationSpecific)wrappedStream.readObject();

            if ( apReq.getApplicationTag() != KRB5_APREQ_ID ) {
                throw new Krb5ApReqException();
            }

            byte[] apReqContents = apReq.getContents();
            apReqStream = new ASN1InputStream(apReqContents);
            ASN1Sequence apReqSeq = ASN1Sequence.getInstance(apReqStream.readObject());
            DERApplicationSpecific innerTicket = (DERApplicationSpecific) (((DERTaggedObject) apReqSeq.getObjectAt(3)).getObject());

            if ( innerTicket.getApplicationTag() != KRB5_TICKET_ID ) {
                throw new Krb5ApReqException();
            }

            innerTicketStream = new ASN1InputStream(innerTicket.getContents());
            ASN1Sequence ticketSeq = ASN1Sequence.getInstance(innerTicketStream.readObject());
            ASN1String realmDERString = (ASN1String) ((DERTaggedObject) ticketSeq.getObjectAt(1)).getObject();
            this.realm = realmDERString.getString();
            final ASN1Sequence sname = ASN1Sequence.getInstance(((DERTaggedObject)ticketSeq.getObjectAt(2)).getObject());
            final ASN1Sequence namelist = ASN1Sequence.getInstance(((DERTaggedObject)sname.getObjectAt(1)).getObject());

            int namesz = namelist.size();
            if ( namesz != 2 ) {
                throw new Krb5ApReqException();
            }

            DERGeneralString protocolDERGeneralString = (DERGeneralString)namelist.getObjectAt(0);
            DERGeneralString hostDERGeneralString = (DERGeneralString)namelist.getObjectAt(1);

            this.protocol = protocolDERGeneralString.getString();
            this.host = hostDERGeneralString.getString();

        } catch (IOException e) {
            LOGGER.log(Level.WARNING, "Could not parse the kerberos token.", e);
            throw new Krb5ApReqException();
        } finally {
            ResourceUtils.closeQuietly(ain);
            ResourceUtils.closeQuietly(wrappedStream);
            ResourceUtils.closeQuietly(apReqStream);
            ResourceUtils.closeQuietly(innerTicketStream);
        }
    }

    private byte[] removeSPNEGOWrapperIfExists(byte[] possiblySpnegoToken) {
        if(GSSSpnego.hasSpnegoWrapper(possiblySpnegoToken)) {
            LOGGER.info("Found SPNEGO token wrapper. Removing it to parse the Kerberos V5 token.");
            return GSSSpnego.removeSpnegoWrapper(possiblySpnegoToken);
        }
        return possiblySpnegoToken;
    }

    public String getProtocol() { return protocol; }

    public String getHost() { return host; }

    public String getRealm() { return realm; }

    public String getSpn() { return protocol + "/" + host + "@" + realm; }
}
