package com.l7tech.common;

import com.l7tech.util.HexUtils;
import com.l7tech.util.Pair;
import com.l7tech.common.io.CertUtils;

import java.security.PrivateKey;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.cert.X509Certificate;
import java.security.cert.CertificateException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.InvalidKeySpecException;
import java.io.IOException;

/**
 * Various test private keys (and self-signed certs), for unit tests that need quick access to one and
 * don't want to have to spend the CPU cycles and/or RNG entropy to generate a new one each time.
 */
public class TestKeys {

    // --- BEGIN GENERATED CODE; generated by manually running TestKeysGenerator, then copy/pasting ---

    public static final String RSA_512_CERT_X509_B64 =
        "MIIBjDCCATagAwIBAgIIYAHMhsRnmnYwDQYJKoZIhvcNAQEFBQAwFzEVMBMGA1UEAwwMdGVzdF9y" +
        "c2FfNTEyMB4XDTA5MTIxNjIzNDExN1oXDTM0MTIxMDIzNDExN1owFzEVMBMGA1UEAwwMdGVzdF9y" +
        "c2FfNTEyMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKz8tZ7UTzxQ+tZzHUUlewdSasfC6XTRV20K" +
        "C/TTPUF9sCyir1aykmrf0pcvuUBfdBpe9nwC4xbsiaXj9J2RSTcCAwEAAaNmMGQwDgYDVR0PAQH/" +
        "BAQDAgXgMBIGA1UdJQEB/wQIMAYGBFUdJQAwHQYDVR0OBBYEFIUySQa5BcpHUusPUp0lF0oQS5yA" +
        "MB8GA1UdIwQYMBaAFIUySQa5BcpHUusPUp0lF0oQS5yAMA0GCSqGSIb3DQEBBQUAA0EAYNMls9iP" +
        "bGlWIZYC73qXDtjzLyvVwT+TDEIcpT/uO3kUkrldnUYI8CR+ble/kV3imq6r/Oaw2b2w+lvHga0Y" +
        "LA==";

    public static final String RSA_512_KEY_PKCS8_B64 =
        "MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEArPy1ntRPPFD61nMdRSV7B1Jqx8Lp" +
        "dNFXbQoL9NM9QX2wLKKvVrKSat/Sly+5QF90Gl72fALjFuyJpeP0nZFJNwIDAQABAkB5uNyHpXcX" +
        "xxep/JhVBnmafljatYEWjROKi248WMOap5DVmA3YgdHfpJx3Qdtof+VZlRKa0kQI3doFCt/JzfX5" +
        "AiEA3dgKCWuZbYqoGvFLEJ6LWAPbC5qX+lExaEC0/vjP+ksCIQDHnvwewFDfL/RS0d0SZ8bJjyB8" +
        "hqusB2X9fWHfL0SZRQIhAJ31XfAnNS/SMrA8bv5+ZSleVXGFugD6HvvkVvvVngDRAiBGcK2a1FY1" +
        "S6C1kOSn2ALnoR/fkU4G2F1/A72DmhRk2QIgQB6qn1V/WaUztabeaLnLg/WPmr2PdR4MZdYTgax8" +
        "ufA=";

    public static final String RSA_768_CERT_X509_B64 =
        "MIIBzDCCAVagAwIBAgIIVX44sjtK0aEwDQYJKoZIhvcNAQEMBQAwFzEVMBMGA1UEAwwMdGVzdF9y" +
        "c2FfNzY4MB4XDTA5MTIxNjIzNDExOFoXDTM0MTIxMDIzNDExOFowFzEVMBMGA1UEAwwMdGVzdF9y" +
        "c2FfNzY4MHwwDQYJKoZIhvcNAQEBBQADawAwaAJhAIRepsCCBQHHaGRf+y8dCk31cNd/GpRLG2w5" +
        "VPz/z8jL42cEhOXNTYFE1xM0Od1vWASB3vDVyPi3T71GeGt71bIWQTcsWcH681KYRS8DN54ZRe0v" +
        "r08FFRahEwjqTQw5bQIDAQABo2YwZDAOBgNVHQ8BAf8EBAMCBeAwEgYDVR0lAQH/BAgwBgYEVR0l" +
        "ADAdBgNVHQ4EFgQUByTM0C7KPXVP4pzOt2bB+6CRe0owHwYDVR0jBBgwFoAUByTM0C7KPXVP4pzO" +
        "t2bB+6CRe0owDQYJKoZIhvcNAQEMBQADYQAxk1ULshWoxVQlOodLffySD3oAlD2NsMO234/54ewi" +
        "zXziIV8FmY2qfaqhiw/fhUsh6Pzw31Be2KeOUmbg1pEk8tR0yHvmUmN7S/2j5CfJSJUN9sEUMbSU" +
        "xUFscJVtkKo=";

    public static final String RSA_768_KEY_PKCS8_B64 =
        "MIIB4wIBADANBgkqhkiG9w0BAQEFAASCAc0wggHJAgEAAmEAhF6mwIIFAcdoZF/7Lx0KTfVw138a" +
        "lEsbbDlU/P/PyMvjZwSE5c1NgUTXEzQ53W9YBIHe8NXI+LdPvUZ4a3vVshZBNyxZwfrzUphFLwM3" +
        "nhlF7S+vTwUVFqETCOpNDDltAgMBAAECYCEbJyuImUX7oJFSLBl5cuVSmJldEcG7Ey27HRV1yXsX" +
        "+1T9nVt4QIUvOXd1HW/Tc9wET0FkDR2gJt1C0Ab/iuhhilw5aDZ/+zDQxlc0sUZ6U9cD61zm5Er0" +
        "+5tQyQYdgQIxANUFaluOEsWPSborHIbQKZF9gEywqacHZfX0wsDEGIeaiUzd5IFvDJ2d3Yu6O4S5" +
        "4QIxAJ8Tkvcnx6qJ5VkHQPBgHMSVBlvUOKxi3myV50tKz+J6A98n4d/HBlXZ878vSEHpDQIwcUu4" +
        "DYm6oihbZhCX03vTH/ZHzoIHOTbOG8pZ6nxhL34ZmDBL4CtX4lycADzEewsBAjAUZ1hUZz/O+fz2" +
        "3F1R96H4/PxhzuiuA8hvuRJ/r8rWS7wvZVgtccO4Q0pmXVQxUAkCMEabiUTPM6ZVyF2WZX/A7yCO" +
        "emb3oHTfs5WybVdPKP2IYpDGR341d4gT0c+ecrw1+A==";

    public static final String RSA_1024_CERT_X509_B64 =
        "MIICFDCCAX2gAwIBAgIJANA/LVIWYlZMMA0GCSqGSIb3DQEBDAUAMBgxFjAUBgNVBAMMDXRlc3Rf" +
        "cnNhXzEwMjQwHhcNMDkxMjE2MjM0MTE4WhcNMzQxMjEwMjM0MTE4WjAYMRYwFAYDVQQDDA10ZXN0" +
        "X3JzYV8xMDI0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCDh9hs9BnqyPvL7qoHARHjKwq9" +
        "ZwGeeWDU+oed9H4/Qjnw5PZ54ZgXfU+pEisDxADHfvHXnMrUNuSOXNaH1Lyg+EjOWwQVRW7EbQFK" +
        "paMP6d6FLy70/ErA616i1dPE+gmdtQEZiAqoe+5gch0oZVVu5V6cREFcjzVSv3K5Uo5PhQIDAQAB" +
        "o2YwZDAOBgNVHQ8BAf8EBAMCBeAwEgYDVR0lAQH/BAgwBgYEVR0lADAdBgNVHQ4EFgQU3bG81B25" +
        "MHuoBRi9apZWR2bVqHMwHwYDVR0jBBgwFoAU3bG81B25MHuoBRi9apZWR2bVqHMwDQYJKoZIhvcN" +
        "AQEMBQADgYEADeL5oHQBkkqkojQ+GQBFOpYuDq6yi4QkAe1CKlt4ieXczmoPd1NmhWY8U+AyORdu" +
        "9I8H+N/OAwfCHNqS9a7xBjd55gObOJ1ZDYJEVXSJ/gx0vRwm166BY5A6hF/7F24Me5ItDiwQbK1c" +
        "J7t7E2C6q1B2qkLUujTACbCAyCpv5B4=";

    public static final String RSA_1024_KEY_PKCS8_B64 =
        "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIOH2Gz0GerI+8vuqgcBEeMrCr1n" +
        "AZ55YNT6h530fj9COfDk9nnhmBd9T6kSKwPEAMd+8decytQ25I5c1ofUvKD4SM5bBBVFbsRtAUql" +
        "ow/p3oUvLvT8SsDrXqLV08T6CZ21ARmICqh77mByHShlVW7lXpxEQVyPNVK/crlSjk+FAgMBAAEC" +
        "gYAE60ix0nNBr6CTIOrk9ipIF60AJmEOHzX64R+/TYyHKx/lnXqGVmSMxFf9V7uaGXN6Aopi6O9A" +
        "/oiPtnMjg1ZGlP7ONFyaf0ZsaMs4jm7FAfDHtnaemEJkDEadYSvppN8oB1bPm1NYe6mAvaui3PiM" +
        "EGkkq+MSgms5j8RFHyUvBQJBANYoloJJ6hfhRGJiTSyP1TRYoKHrf2mVFnEyHxALhK32+TnasKZI" +
        "CkVLcAPhqfnNQKwn3nATfc0ZXeI9BMTwHNMCQQCdOoSZCNUFjslXOC1zS+XtoiE1znjtlIYqGR+h" +
        "TLWdJQkdyoB5ATOtL3uj+7muwMmKc7rmsW6imAqxxwDBmctHAkABMVatQRYhreqAlcWSQvbQBNJY" +
        "NISQJPlsBfhwUXAau+5laRdkxa/w9NuZ2e7lakQ68Tnm6+TeeI6yTN6y7hdrAkBmgWtHdomjSPcd" +
        "RQPkwlvSNLygHs+aXRWnRp/ngmJ5ZFbwNEDUIyN0yps6SvhA5XHAMTluA8nUeXmnc82batArAkEA" +
        "gW39CjSVbeUpgwEpt2CAz0qa08IQ56clJcyCHiwLQelfezLrQkwX+k6Lkf11JxOsf9a4A2ToElml" +
        "KyZu+sPE/g==";

    public static final String RSA_1536_CERT_X509_B64 =
        "MIICkzCCAbygAwIBAgIIfWqcn+A0noswDQYJKoZIhvcNAQEMBQAwGDEWMBQGA1UEAwwNdGVzdF9y" +
        "c2FfMTUzNjAeFw0wOTEyMTYyMzQxMThaFw0zNDEyMTAyMzQxMThaMBgxFjAUBgNVBAMMDXRlc3Rf" +
        "cnNhXzE1MzYwgd8wDQYJKoZIhvcNAQEBBQADgc0AMIHJAoHBAKao+zmD0aGU01+3A5oP0bCbIkXs" +
        "K6kMVmvPLIkDF8CqNiy8cbo8vOzhioxgKvAMVyUfS/2N4xxsYRBw4QgPkWdYx5h2TzX0xFmrza34" +
        "PbLPfwmU9OT/EgWxxLebsnZOUSBeVzXoCp7IVVlnf9lWSr0fpRVKOug6wgCKHb3xlr85+cvfwesO" +
        "Dd0ioCnL5kg87/rHOQ4bdLAe8gKwm4iczr/IwMa1aFKezAwLclFskq1m3W+ckSnGauPtBLtZc6fb" +
        "fwIDAQABo2YwZDAOBgNVHQ8BAf8EBAMCBeAwEgYDVR0lAQH/BAgwBgYEVR0lADAdBgNVHQ4EFgQU" +
        "ZC4c/Jqu0OqKm4hhU/rV/mcEzBswHwYDVR0jBBgwFoAUZC4c/Jqu0OqKm4hhU/rV/mcEzBswDQYJ" +
        "KoZIhvcNAQEMBQADgcEAU6snBQGrdeQeDNATet43UqmtXx8Dv6TLtIEi9Wx9gZE/9nCaFRpvn9Fl" +
        "cgESzKCvKpWWnbf6PN3vqDuNnyddZJfnYLSVxxhhx20sSUvAOlVGvU+igQdxNnS84FDFobE0WYzH" +
        "DQeBAk8bxd6sCiPJgb4mcyPjaW3FJXfvV2hEevVMF4B5JHzcSVtoTJ8dnDDEVeRWYKM4buWE8owh" +
        "M7k06VZ4UbqXmGilfpM+SsTL7qraLKH8cW+ZxtVbZQVczuly";

    public static final String RSA_1536_KEY_PKCS8_B64 =
        "MIIDlgIBADANBgkqhkiG9w0BAQEFAASCA4AwggN8AgEAAoHBAKao+zmD0aGU01+3A5oP0bCbIkXs" +
        "K6kMVmvPLIkDF8CqNiy8cbo8vOzhioxgKvAMVyUfS/2N4xxsYRBw4QgPkWdYx5h2TzX0xFmrza34" +
        "PbLPfwmU9OT/EgWxxLebsnZOUSBeVzXoCp7IVVlnf9lWSr0fpRVKOug6wgCKHb3xlr85+cvfwesO" +
        "Dd0ioCnL5kg87/rHOQ4bdLAe8gKwm4iczr/IwMa1aFKezAwLclFskq1m3W+ckSnGauPtBLtZc6fb" +
        "fwIDAQABAoHAPoMHqG0fRmJSXoaBHVptprapxlxti/0KtWmCJOo6EJRHucP9TIPXwWpf04OG139p" +
        "eI0irbp4w4KLbeVJIwLj4UXVqARIdc6Xj6L3hRel3Nojpm5u5S4fjm89gDkwWVvKSmtmtJ0tdnjN" +
        "ybeauLnku96HoEIpia+k5XC5qn/YcmY2nHsINSFGG2QAEixTyTvRePah1QSavB+nRyCoyAl98993" +
        "HVP05cbx53v1VYP0/J0pxDXJsrm6Y6qZzlVDlsIBAmEA5bbIO9cTH7R/4lzToWKNvgVauojz4xgb" +
        "VcT4hKbs2MrDrUMvYcCvVZeOFcSC0HZU65l7OcD3vpD/7Y9hFYS91l0gosGlJJO61JhFUI+BrG2n" +
        "5VOC3Qd1Zkocr4r7x7X/AmEAubsawUopDOpCCYh4hPfzgalta8txmDZOjWKobdNZgCPYIqKa/azP" +
        "7q8BRJ301THSeaF5zt7//MGLHtDKYuhZQUJawNcZtAMdOuNTz9dasC3b5uR01Pf5nv4uakBg9tqB" +
        "AmAMBqiu8VCP/VwglqmBrm4rP46Da34RKobr05cLIs4Nf3gFDxpg7LyBJ6EJpLMQhNFnUC6yVFbk" +
        "BCVR44q6nKtvmIqH2slxg8ZpMNuYHxsz0r3SdK/KMITF6SVdT1JlHzMCYQCHGJfPfNf7MvIx6Phx" +
        "D8Ip0EltHSBVbTsaEGce65qwYGI4XzqJxofAv78WYCbUZFcKbfAiD4b4HPfKxGhSJVu24kMM/ekO" +
        "TS2Xxf8SsTyf5duMSSTKPE1v3sd4NbfSFwECYBOziHhR3yQ5B6rvxxoSkvXcgR6H0XQ2mHwXOje8" +
        "pRMHvm21ZkMUULvFjas2s2Qobz3eG9LolBFulBrrOKlEutKnX0TCpNpyMYTcsLVRz/yKvu4VcwyY" +
        "CaIC97eQEX4+ig==";

    public static final String RSA_2048_CERT_X509_B64 =
        "MIIDGDCCAgCgAwIBAgIIB2dtRKOWrgswDQYJKoZIhvcNAQEMBQAwGDEWMBQGA1UEAwwNdGVzdF9y" +
        "c2FfMjA0ODAeFw0wOTEyMTYyMzQxMThaFw0zNDEyMTAyMzQxMThaMBgxFjAUBgNVBAMMDXRlc3Rf" +
        "cnNhXzIwNDgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxNW9CQzGqUV38EirNbD0x" +
        "xEVIamH4WGUeCbCYq7np1FWz7uBG137duU7ZOr1oMgkdaCv1l2D8mNc5u6S9pgOptNFSZRodxB9N" +
        "13vl1pV8b+ZmltN7zgEYVNNbK7DegonNgF8qjzol03gU5z1qAAt1txMrDO5yFwSJz5NMk4jCudvA" +
        "3ZCnI++Cm3FtZpssKY6ma41M4i4PPtsatIF+3ao6zqfrXaRQgS8gcONgiGn0PNDJZBJgD6CTlzk2" +
        "kVC2SQts6EILjkXqumvA06XCEe1h3AA0QUROzaNpJ5zmr9502itTEv28kyVrr2aMDgK0QjXb3jlb" +
        "foiY8qSkxivoYRpbAgMBAAGjZjBkMA4GA1UdDwEB/wQEAwIF4DASBgNVHSUBAf8ECDAGBgRVHSUA" +
        "MB0GA1UdDgQWBBRNqj1i9aNTI2d/4CX81FGCuHfvbDAfBgNVHSMEGDAWgBRNqj1i9aNTI2d/4CX8" +
        "1FGCuHfvbDANBgkqhkiG9w0BAQwFAAOCAQEAUKvuuvPdjFFEXcdht4GR76W7++MaTc0QUVegTbDT" +
        "+E3CcAfBWqTi7Q6djRSqAOP6xoDmGUpKX4ef3tDonFJ+nz8HPAkxV//yAVzC7asbfOtMZshrG5YV" +
        "k/WbFzz09YqJbs6JIibMgj6SR7GoYV86YVv80ZT1Zc94AECWid3Thvc1OHzcndRkCBX1b4nkWffX" +
        "cblHP5dXnfISImULWf0R88IEP+G/aLEMfZ5SHWdO5TVgztrXeEnR9Efiz/MSRA8JY4eBywexXjMF" +
        "f0fvJNenDoIY7Dxp3mRqBXf9smKmvF0YqQ29u/l7ZlvF1D2dEhAHqX2yotJISjirZE5VbQKFBw==";

    public static final String RSA_2048_KEY_PKCS8_B64 =
        "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCxNW9CQzGqUV38EirNbD0xxEVI" +
        "amH4WGUeCbCYq7np1FWz7uBG137duU7ZOr1oMgkdaCv1l2D8mNc5u6S9pgOptNFSZRodxB9N13vl" +
        "1pV8b+ZmltN7zgEYVNNbK7DegonNgF8qjzol03gU5z1qAAt1txMrDO5yFwSJz5NMk4jCudvA3ZCn" +
        "I++Cm3FtZpssKY6ma41M4i4PPtsatIF+3ao6zqfrXaRQgS8gcONgiGn0PNDJZBJgD6CTlzk2kVC2" +
        "SQts6EILjkXqumvA06XCEe1h3AA0QUROzaNpJ5zmr9502itTEv28kyVrr2aMDgK0QjXb3jlbfoiY" +
        "8qSkxivoYRpbAgMBAAECggEAKAVqYCuuvslrkW9E7WnhlCjAgO9NuvmztIn5sTEvZqjGxkFPs5Ad" +
        "ndOpBBRpDGwodNS/ANM0Wzfle6tuNEqXDy/ACny83jYZ38mnuKuyzQy0mzy6/H3071rQ9Qk0A7y1" +
        "hIzWcVUxi7NrrkTfMN5buDUlhhaAj5G1O65+lM/JFjjlEH2L6rwfcPAiyD1dyDzjXd4k8acv0JPD" +
        "JANJ2hLjXnOHFDR/cCxCOysdGHQuH9aMIdeNz0JGyiWLD6SP+9va0G49DwSG7xL7bdnbDC812XUo" +
        "wqVhksg4yjRkvL3ZExG25XQwkdJ01QU4atz4QJdqYVy/X/Vt7SG1kJoyMDWKgQKBgQDiIaxbkDnf" +
        "Vr1aDZMUZ3/dKWePclbSqQoUExgfidhYoJn92j+rNbLoIseyBe8nBMeBuLSsyFQJU81ZdvpRaGMH" +
        "jltef/cGY7DZtoPx/WpKjIJxGH0Hk3/kJMWxhcar0eXyuXDj+rNGy6wp7yZFnZlr70SRsD1AxdaE" +
        "x400Vl8RmwKBgQDInYEBMj3TRUhqWspgXEB4cy67zaOh+LYxJTbkLGPi5rm/tX1QxGZJNvT/RZRA" +
        "vQuy/tdJqaZrZWtP/z8AQ/2Ya7zcHu0oqz1YrAIG7WH75ZupOp7SaNbcZ1ojHyQTtmYDTs8ErFK0" +
        "YTEzylpOYjKAQ4uvKcv/XIiuIv/OlrwGQQKBgQDfUqgYiVhONCiujedqaEjDz0dCSIZsZ5rXdoAF" +
        "baom5P0P0gG9ATxduzOCog+sdjDd8N8mIHW1/Hg52aGe0juy06lyq2f3fG7EpFasnzvgweF09d1M" +
        "pSPR2WsQRfCN8a5pxzAxRn7U9QJjK5ade+ZvzQ3n36iulnOkEDtoq8AZ7wKBgQCm6AuVcDRp2sGV" +
        "4rVvGDF3RPVDwKH8Nw11s+2IRrpP4//0VM3O7afgD/4jh8MBXYcnQ8jf+2p+/aEbrFPBJ9AMCM7X" +
        "IE/VvypJ5MnG86bKyUwJrsDGc/0W4FHo2JbOY7lZ1S59R9WDRz2FRjx97Erx1cCYWiDj8xuwLWRA" +
        "f74tQQKBgQCfGlni4CM9YerW+YI8MRbWSydvXPZ3uirRUVmXiODp8XoUbzKeohg4dDw4Ns0VykRJ" +
        "sUTOApGOlL1pxHoTUoxwLLrVa580+RZeDt9b4Q4j9ZuMNbndNUQOqcifv7hHEQTPXEqgTx3i4t6p" +
        "sOX8p9A1peKQeUL75mr1HwLYi+NHig==";

    public static final String EC_secp256r1_CERT_X509_B64 =
        "MIIBkzCCATmgAwIBAgIIOWLQpO+rVREwCQYHKoZIzj0EATAcMRowGAYDVQQDDBF0ZXN0X2VjX3Nl" +
        "Y3AyNTZyMTAeFw0wOTEyMTYyMzQxMTlaFw0zNDEyMTAyMzQxMTlaMBwxGjAYBgNVBAMMEXRlc3Rf" +
        "ZWNfc2VjcDI1NnIxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzp4+a5LF87KqSAMuSNmIVIFL" +
        "SfBWIcMbllIIfQ+vmEBxe302lJVFPFHede2Gf+V+42eei2ZG00IbzlCAMiCo16NmMGQwDgYDVR0P" +
        "AQH/BAQDAgXgMBIGA1UdJQEB/wQIMAYGBFUdJQAwHQYDVR0OBBYEFKj6kjjyOJ04GHkoavFw8ZC9" +
        "dbK6MB8GA1UdIwQYMBaAFKj6kjjyOJ04GHkoavFw8ZC9dbK6MAkGByqGSM49BAEDSQAwRgIhAKjs" +
        "k7G/9oHcSXisTabeem+Jr8Gj+i//kLp6UUhPWiHDAiEA8XKThuCN5oSJQwjgJ5QxrwSkD6B8qihB" +
        "J3V5g7ICnMI=";

    public static final String EC_secp256r1_KEY_PKCS8_B64 =
        "MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCD01OlbRwiLsSLGfSra1CoRJRz/B6ti" +
        "4YD4dovGxtIOHQ==";

    public static final String EC_secp384r1_CERT_X509_B64 =
        "MIIB0zCCAVigAwIBAgIJAKnrAXajzLwoMAoGCCqGSM49BAMDMBwxGjAYBgNVBAMMEXRlc3RfZWNf" +
        "c2VjcDM4NHIxMB4XDTA5MTIxNjIzNDEyMFoXDTM0MTIxMDIzNDEyMFowHDEaMBgGA1UEAwwRdGVz" +
        "dF9lY19zZWNwMzg0cjEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAASp92Vv7qoY0+khqH8o3AY8zO17" +
        "oIc2a9cdsvEqhUET4gmVuEmzjumtXKsNuichgF7v8D7fjcYYY8+df+bOUcoFduRKWMfIZFFThTKG" +
        "PjyK3ZPNhmEVeOpTqCV43JoHNq+jZjBkMA4GA1UdDwEB/wQEAwIF4DASBgNVHSUBAf8ECDAGBgRV" +
        "HSUAMB0GA1UdDgQWBBQ+sq0AVeZtKAcjXIXICsqVoC+MeTAfBgNVHSMEGDAWgBQ+sq0AVeZtKAcj" +
        "XIXICsqVoC+MeTAKBggqhkjOPQQDAwNpADBlAjB6WrVTujB/QSFW7DUeLn1Cq2BWRFdqEvO7gIrb" +
        "+Wc63Z4kUCYAzyvbsbY/hEM6IokCMQC3YWsaZ7uBe94fsDWv5Q4lyPpYyDRgf/7Tb2s+6E/wyckE" +
        "MKAwqiaw+a36GodQWvMA";

    public static final String EC_secp384r1_KEY_PKCS8_B64 =
        "ME4CAQAwEAYHKoZIzj0CAQYFK4EEACIENzA1AgEBBDAhyd5V2T6UYn8t8G4Lj1qaICzJAxNNheJT" +
        "Z1cvDsRYKxdMmcmMGh6Yl5slgqjUXZE=";

    public static final String EC_secp521r1_CERT_X509_B64 =
        "MIICHTCCAX2gAwIBAgIIeFK5zGM+HrYwCgYIKoZIzj0EAwMwHDEaMBgGA1UEAwwRdGVzdF9lY19z" +
        "ZWNwNTIxcjEwHhcNMDkxMjE2MjM0MTIwWhcNMzQxMjEwMjM0MTIwWjAcMRowGAYDVQQDDBF0ZXN0" +
        "X2VjX3NlY3A1MjFyMTCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEAPf/TOVk1tC7kdV8K3dqEEdp" +
        "K26CQ7zyar1eVCbiVRGU+mrYs0262FGsE+A4zGjqWAIxb5Lssw6VarQ4ORVwR+2DAM23LruoY1Sx" +
        "YAAmf/eiI55flmNjcrl/zpVIu/7vUAgPKGpBeslQQEyG4JlqFxP5Qg6yLJNzBI5JAsS2QlaqvSgN" +
        "o2YwZDAOBgNVHQ8BAf8EBAMCBeAwEgYDVR0lAQH/BAgwBgYEVR0lADAdBgNVHQ4EFgQUu2bmgS+E" +
        "vXvBVUndCmtjP3hf5QowHwYDVR0jBBgwFoAUu2bmgS+EvXvBVUndCmtjP3hf5QowCgYIKoZIzj0E" +
        "AwMDgY0AMIGHAkIB7cJgTC75sMZ+u78W2vWzOeuvMbAYM/34F7KU3CkwwKmEPThN/Ek4ZvIxqPC7" +
        "qxxTlqLwl1w5Z74qMDIztItXe5ICQSYKuWlyc9VdrtCuWd7T7OXPziov0TxYTl01ey9y9QYRdsMR" +
        "l/OCf5dwQpGuRoYfosHGGOGN9KuyB00pVgwGeaJwAAA=";

    public static final String EC_secp521r1_KEY_PKCS8_B64 =
        "MF8CAQAwEAYHKoZIzj0CAQYFK4EEACMESDBGAgEBBEGBJXY/QTar1ibN0T0X4g8hdXUT+cR2rEOz" +
        "iQPAKaQh751pXeVJSKXORoboYfO9JwbNmF8nPlPKUpLRwxvWx2dRWQ==";

    public static final String DSA_1024_CERT_X509_B64 =
        "MIIC0TCCApGgAwIBAgIIPn/bpX9NtT0wCQYHKoZIzjgEAzAYMRYwFAYDVQQDDA10ZXN0X2RzYV8x" +
        "MDI0MB4XDTA5MTIxNjIzNDEyMFoXDTM0MTIxMDIzNDEyMFowGDEWMBQGA1UEAwwNdGVzdF9kc2Ff" +
        "MTAyNDCCAbcwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+A" +
        "tlEmaUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb" +
        "+DtX58aophUPBPuD9tPFHsMCNVQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5" +
        "gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jrqgvlXTAs9B4JnUVlXjrrUWU/mcQcQ" +
        "gYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO8yk8b6o" +
        "UZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GEAAKBgGGsAH9G/0GsDHAF3hI9ypl8Q9rbrkv+" +
        "ozsqyp5mvvwvou8Lax1H1T1bLweQF7SqnYIIueRu1ytE8lpqPbeZWKiii327RnKCLj05gp94S8dM" +
        "S5lzwj61KL7iZk7EbL0KbrFTjvyLhFxdo0YVg/qhDiPFaPMVNfAHxlnGrqU29tD3o2YwZDAOBgNV" +
        "HQ8BAf8EBAMCBeAwEgYDVR0lAQH/BAgwBgYEVR0lADAdBgNVHQ4EFgQUDSJdgUTMXLPRomOq/jgo" +
        "XLqS1JwwHwYDVR0jBBgwFoAUDSJdgUTMXLPRomOq/jgoXLqS1JwwCQYHKoZIzjgEAwMvADAsAhRO" +
        "PZUsOr+6fcTsq080hvMZiPFxrAIUMUi6AlI/OsuyPTYk7CMRe5kNves=";

    public static final String DSA_1024_KEY_PKCS8_B64 =
        "MIIBTAIBADCCASwGByqGSM44BAEwggEfAoGBAP1/U4EddRIpUt9KnC7s5Of2EbdSPO9EAMMeP4C2" +
        "USZpRV1AIlH7WT2NWPq/xfW6MPbLm1Vs14E7gB00b/JmYLdrmVClpJ+f6AR7ECLCT7up1/63xhv4" +
        "O1fnxqimFQ8E+4P208UewwI1VBNaFpEy9nXzrith1yrv8iIDGZ3RSAHHAhUAl2BQjxUjC8yykrmC" +
        "ouuEC/BYHPUCgYEA9+GghdabPd7LvKtcNrhXuXmUr7v6OuqC+VdMCz0HgmdRWVeOutRZT+ZxBxCB" + 
        "gLRJFnEj6EwoFhO3zwkyjMim4TwWeotUfI0o4KOuHiuzpnWRbqN/C/ohNWLx+2J6ASQ7zKTxvqhR" +
        "kImog9/hWuWfBpKLZl6Ae1UlZAFMO/7PSSoEFwIVAJANKzH8+knGGXNWLzeg5JoQJtMJ";

    public static final String DSA_1024_NO_SKI_CERT_X509_B64 =
        "MIICszCCAnKgAwIBAgIIWfC3mJx/u3YwCQYHKoZIzjgEAzAYMRYwFAYDVQQDDA10ZXN0X2RzYV8x" +
        "MDI0MB4XDTE0MTAyMTIzMDUxOVoXDTM5MTAxNTIzMDUxOVowGDEWMBQGA1UEAwwNdGVzdF9kc2Ff" +
        "MTAyNDCCAbcwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+A" +
        "tlEmaUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb" +
        "+DtX58aophUPBPuD9tPFHsMCNVQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5" +
        "gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jrqgvlXTAs9B4JnUVlXjrrUWU/mcQcQ" +
        "gYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO8yk8b6o" +
        "UZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GEAAKBgC9zseTNnYOvsD0EYu6Xk4XPUgztdoTd" +
        "VEVxPZWQMWok+xOOv8mpnnt0jS5qnRfZe83Qls+oYY12/ef2KAeTP+KAmn2IpJVSQAHB7XpMfjDA" +
        "OKe9bA20JHI0RhDxffEgWnP9AOON2l2hOTQXMLP81DI77lfyqR0JAYwiDF9PJla4o0cwRTAOBgNV" +
        "HQ8BAf8EBAMCBeAwEgYDVR0lAQH/BAgwBgYEVR0lADAfBgNVHSMEGDAWgBSJDhh5GZ2XaXF0gqS7" +
        "Ym+0/RubpjAJBgcqhkjOOAQDAzAAMC0CFQCW5Yv+GJ/SVOGt0G4YB/ZdDNf5PwIUb8TpE0kJ2rBE" +
        "ZRaUZI4CIsI8b4w=";

    public static final String DSA_1024_NO_SKI_KEY_PKCS8_B64 =
        "MIIBSwIBADCCASwGByqGSM44BAEwggEfAoGBAP1/U4EddRIpUt9KnC7s5Of2EbdSPO9EAMMeP4C2" +
        "USZpRV1AIlH7WT2NWPq/xfW6MPbLm1Vs14E7gB00b/JmYLdrmVClpJ+f6AR7ECLCT7up1/63xhv4" +
        "O1fnxqimFQ8E+4P208UewwI1VBNaFpEy9nXzrith1yrv8iIDGZ3RSAHHAhUAl2BQjxUjC8yykrmC" +
        "ouuEC/BYHPUCgYEA9+GghdabPd7LvKtcNrhXuXmUr7v6OuqC+VdMCz0HgmdRWVeOutRZT+ZxBxCB" +
        "gLRJFnEj6EwoFhO3zwkyjMim4TwWeotUfI0o4KOuHiuzpnWRbqN/C/ohNWLx+2J6ASQ7zKTxvqhR" +
        "kImog9/hWuWfBpKLZl6Ae1UlZAFMO/7PSSoEFgIUYFxUGfHl21TO+HDpW/43OGDeQgM=";

    // --- END GENERATED CODE; generated by manually running TestKeysGenerator, then copy/pasting ---

    /**
     * Get the named cert and privatekey.
     *
     * @param name name, ie "RSA_1024" or "EC_secp521r1".  Required.
     * @return the pregenerated cert with that name.  Never null.
     * @throws IllegalArgumentException if no pregenerated key+cert with that name is available
     * @throws RuntimeException if the requested test data exists but we are unable to decode it.
     */
    public static Pair<X509Certificate, PrivateKey> getCertAndKey(String name) {
        try {
            String certb64 = (String)TestKeys.class.getField(name + "_CERT_X509_B64").get(null);
            String keyb64 = (String)TestKeys.class.getField(name + "_KEY_PKCS8_B64").get(null);
            String alg = name.split("\\_", 2)[0];
            return new Pair<>(getCert(certb64), getKey(alg, keyb64));
        } catch (NoSuchFieldException e) {
            throw new IllegalArgumentException("No pregen key+cert named " + name, e);
        } catch (IllegalAccessException | IOException | InvalidKeySpecException |
                NoSuchAlgorithmException | CertificateException e) {
            throw new RuntimeException(e);
        }
    }

    public static X509Certificate getCert(String base64) throws IOException, CertificateException {
        return CertUtils.decodeFromPEM(base64, false);
    }

    public static PrivateKey getKey(String algorithm, String base64) throws NoSuchAlgorithmException, InvalidKeySpecException {
        return KeyFactory.getInstance(algorithm).generatePrivate(new PKCS8EncodedKeySpec(HexUtils.decodeBase64(base64, true)));
    }
}
