#!/bin/bash
#
# Startup script for the SecureSpan Process Controller
#
# chkconfig: - 99 01
# description: Layer 7 SecureSpan Process Controller Daemon
# processname: sspc

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
USER=$(whoami)
if [ $USER != "root" ] ; then
    echo "Need to be root to run this script";
    exit
fi

# Config
PID_FILE="sspcd"
PC_USER="layer7"
PC_SCRIPT="/opt/SecureSpan/Gateway/controller/bin/processcontroller.sh"

start() {
        if [ ! -x "${PC_SCRIPT}" ] ; then
            echo "Service script not found or not executable."
            exit 5
        fi

        echo -n $"Starting Gateway Services: "
        daemon --check "${PID_FILE}" "${PC_SCRIPT}" "${PC_USER}" "/var/run/${PID_FILE}.pid"
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/sspc
        return $RETVAL
}

stop() {
        echo -n $"Shutting down Gateway Services: "
        killproc "${PID_FILE}"
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/sspc
        return $RETVAL
}

status() {
        if [ -f "/var/run/${PID_FILE}.pid" ] ; then
            PID=$(<"/var/run/${PID_FILE}.pid")
            if [ ! -z "${PID}" ] && [ -d "/proc/${PID}" ] ; then
                echo "ssg (pid $PID) is running..."
                return 0
            else
                echo "ssg dead but pid file exists"
                return 1
            fi
        else
            echo "ssg is stopped"
            return 3
        fi
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
        sleep 5
	start
	;;
  status)
        status sspcd
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit $RETVAL
